import {useEffect,useRef,useState} from 'react'
import {Keyboard,Microphone,PaperPlaneTilt} from '@phosphor-icons/react'
type Session={held:boolean,cancel:boolean,y:number,started:number,stream?:MediaStream,recorder?:MediaRecorder,speech?:any,text:string,chunks:Blob[],timer?:ReturnType<typeof setTimeout>}
export function ChatComposer({onText,onVoice}:{onText:(text:string)=>void,onVoice:(blob:Blob,text:string)=>void}){
 const [mode,setMode]=useState<'voice'|'text'>('voice'),[text,setText]=useState(''),[status,setStatus]=useState<'idle'|'permission'|'recording'|'cancel'>('idle'),[error,setError]=useState('')
 const current=useRef<Session|null>(null),alive=useRef(true)
 function finish(cancel=false){const s=current.current;if(!s)return;s.held=false;s.cancel=s.cancel||cancel;clearTimeout(s.timer);s.speech?.stop();if(s.recorder?.state==='recording')s.recorder.stop();else s.stream?.getTracks().forEach(t=>t.stop());if(alive.current)setStatus('idle')}
 useEffect(()=>{alive.current=true;const abort=()=>finish(true);const hidden=()=>{if(document.hidden)abort()};window.addEventListener('blur',abort);document.addEventListener('visibilitychange',hidden);return()=>{alive.current=false;abort();window.removeEventListener('blur',abort);document.removeEventListener('visibilitychange',hidden)}},[])
 async function begin(y:number){if(current.current?.held||current.current?.recorder?.state==='recording')return;const s:Session={held:true,cancel:false,y,started:0,text:'',chunks:[]};current.current=s;setError('');setStatus('permission');try{
 const stream=await navigator.mediaDevices.getUserMedia({audio:true});s.stream=stream;if(!s.held||!alive.current||current.current!==s){stream.getTracks().forEach(t=>t.stop());return}
 const r=new MediaRecorder(stream);s.recorder=r;r.ondataavailable=e=>{if(e.data.size)s.chunks.push(e.data)};r.onstop=()=>{stream.getTracks().forEach(t=>t.stop());if(!alive.current||s.cancel)return;if(Date.now()-s.started<600){setError('说话时间太短，请按住再说一次。');return}const blob=new Blob(s.chunks,{type:r.mimeType});if(blob.size)onVoice(blob,s.text.trim());else setError('没有录到声音，请再试一次。')};r.onerror=()=>{finish(true);setError('录音中断，请再试一次。')};r.start();s.started=Date.now();setStatus('recording');s.timer=setTimeout(()=>{if(current.current===s)finish()},60000)
 const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(SR){try{const a=new SR();s.speech=a;a.lang='zh-CN';a.continuous=true;a.onresult=(e:any)=>{for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)s.text+=e.results[i][0].transcript};a.onerror=()=>{};a.start()}catch{/* Audio still retained when speech recognition is unavailable. */}}
 }catch{s.stream?.getTracks().forEach(t=>t.stop());s.held=false;if(alive.current){setStatus('idle');setError('请允许麦克风权限，或切换键盘打字。')}}}
 return <><form className="chat-composer" onSubmit={e=>{e.preventDefault();if(text.trim()){onText(text.trim());setText('')}}}>
 {error&&<div className="composer-error" role="alert">{error}<button type="button" aria-label="关闭提示" onClick={()=>setError('')}>×</button></div>}
 <button type="button" className="input-mode" disabled={status!=='idle'} aria-label={mode==='voice'?'切换打字':'切换语音'} onClick={()=>{setMode(mode==='voice'?'text':'voice');setError('')}}>{mode==='voice'?<Keyboard size={29}/>:<Microphone size={29}/>}</button>
 {mode==='text'?<><input aria-label="给小叙留言" placeholder="问问小叙" value={text} onChange={e=>setText(e.target.value)}/><button className="send-text" aria-label="发送问题" disabled={!text.trim()}><PaperPlaneTilt size={26}/></button></>:<button type="button" className={`hold-to-talk ${status}`} aria-label="按住说话" onContextMenu={e=>e.preventDefault()} onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);void begin(e.clientY)}} onPointerMove={e=>{const s=current.current;if(!s?.held||!s.started)return;s.cancel=s.y-e.clientY>65;setStatus(s.cancel?'cancel':'recording')}} onPointerUp={()=>finish()} onPointerCancel={()=>finish(true)} onLostPointerCapture={()=>{if(current.current?.held)finish(true)}} onKeyDown={e=>{if((e.key===' '||e.key==='Enter')&&!e.repeat){e.preventDefault();void begin(0)}}} onKeyUp={e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();finish()}}}>{status==='permission'?'正在打开麦克风…':status==='cancel'?'松开取消':status==='recording'?'松开发送':'按住说话'}</button>}
 </form>{status==='recording'||status==='cancel'?<div className={`voice-overlay ${status}`} role="status"><Microphone size={40}/><strong>{status==='cancel'?'松开，取消这条语音':'正在听您说'}</strong><span>{status==='cancel'?'移回按钮可继续':'松开发送 · 上滑取消'}</span></div>:null}</>
}
