import React,{useEffect,useRef,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {Camera,Images,Microphone,ArrowLeft,ArrowRight,Check,PaperPlaneTilt,Trash,UserCircle,CaretRight,Gear,UsersThree,TextAa,ShieldCheck} from '@phosphor-icons/react'
import './style.css'
import {Contacts,ACCOUNTS} from './Contacts'
import {ChatComposer} from './ChatComposer'
type Page='fragment'|'daily'|'people'|'review'|'done'|'ai'|'history'|'me'|'sent'|'contacts'|'settings'|'profile'|'privacy'
type Photo={id:string,url:string}
function App(){
 const[page,setPage]=useState<Page>('fragment'),[kind,setKind]=useState<'fragment'|'daily'>('fragment'),[photos,setPhotos]=useState<Photo[]>([]),[words,setWords]=useState(''),[tags,setTags]=useState<string[]>([]),[people,setPeople]=useState<string[]>([]),[error,setError]=useState(''),[recording,setRecording]=useState(false),[voice,setVoice]=useState(''),[chat,setChat]=useState<{who:string,text:string,audio?:string}[]>([{who:'ai',text:'您好，我是小叙。哪里不会用，可以问我。'}]),[busy,setBusy]=useState(false)
 const [history,setHistory]=useState<any[]>([]),[writing,setWriting]=useState(false)
 const readLocal=(key:string,fallback:any)=>{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}
 const [profile,setProfile]=useState(()=>readLocal('elder-profile',{name:'陈明远',avatar:'./images/teacher.png'})),[profileName,setProfileName]=useState(''),[profileAvatar,setProfileAvatar]=useState('')
 const [largeText,setLargeText]=useState<boolean>(()=>readLocal('elder-large-text',false))
 const persist=(key:string,value:any)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{setError('保存失败，请检查设备空间后重试。');return false}}
 const editProfile=()=>{setProfileName(profile.name);setProfileAvatar(profile.avatar);go('profile')}
 const drafts=useRef<Record<string,any>>({})
 const picker=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),chunks=useRef<Blob[]>([]),speech=useRef<any>(null),timer=useRef<ReturnType<typeof setTimeout>>(),urls=useRef<string[]>([])
 const blobUrl=(b:Blob)=>{const u=URL.createObjectURL(b);urls.current.push(u);return u}
 useEffect(()=>()=>{clearTimeout(timer.current);speech.current?.stop();if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());urls.current.forEach(URL.revokeObjectURL)},[])
 const go=(p:Page)=>{setError('');setPage(p);window.scrollTo(0,0)}
 const start=(k:'fragment'|'daily')=>{if(k!==kind){drafts.current[kind]={photos,words,tags,people,voice};const d=drafts.current[k]||{};setPhotos(d.photos||[]);setWords(d.words||'');setTags(d.tags||[]);setPeople(d.people||[]);setVoice(d.voice||'')}setKind(k);go(k)}
 const upload=(files:FileList|null)=>{if(!files)return;const list=Array.from(files);if(list.some(f=>!f.type.startsWith('image/')||f.size>20*1024*1024)){setError('请选择20MB以内的照片。');return}if(photos.length+list.length>3){setError('一次最多放3张照片，您可以先去掉一张。');return}setPhotos(p=>[...p,...list.map(f=>({id:crypto.randomUUID(),url:blobUrl(f)}))]);setError('')}
 async function record(){if(recording){recorder.current?.stop();speech.current?.stop();return}try{setError('');const s=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=s;const r=new MediaRecorder(s);recorder.current=r;chunks.current=[];r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=()=>{clearTimeout(timer.current);speech.current?.stop();setVoice(blobUrl(new Blob(chunks.current,{type:r.mimeType})));s.getTracks().forEach(t=>t.stop());setRecording(false)};r.start();setRecording(true);timer.current=setTimeout(()=>{if(r.state==='recording')r.stop()},60000);const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(SR){const a=new SR();speech.current=a;a.lang='zh-CN';a.continuous=true;a.onresult=(e:any)=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)t+=e.results[i][0].transcript;if(t){setWords(w=>(w+' '+t).trim().slice(0,500));if(kind==='fragment')setTags(old=>Array.from(new Set([...old,...['家人','朋友','工作','旅行','从前的家'].filter(tag=>t.includes(tag))])))}};a.onerror=()=>{};try{a.start()}catch{speech.current=null}}}catch{stream.current?.getTracks().forEach(t=>t.stop());setRecording(false);setError('暂时无法录音。请允许麦克风权限，或在下面写一句话。')}}
 const stop=()=>{if(recorder.current?.state==='recording')recorder.current.stop();speech.current?.stop()}
 const toggle=(v:string,arr:string[],set:(a:string[])=>void)=>set(arr.includes(v)?arr.filter(x=>x!==v):[...arr,v])
 async function save(){if(busy)return;setBusy(true);setError('');try{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('sgx-elder-demo',1);r.onupgradeneeded=()=>r.result.createObjectStore('items',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});const item={id:crypto.randomUUID(),kind,words,tags,recipientIds:people,people:people.map(id=>ACCOUNTS.find(a=>a.id===id)?.name||id),createdAt:new Date().toISOString(),photos:await Promise.all(photos.map(async p=>(await fetch(p.url)).blob())),voice:voice?await(await fetch(voice)).blob():null};await new Promise<void>((resolve,reject)=>{const t=db.transaction('items','readwrite');t.objectStore('items').add(item);t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error)});db.close();go('done')}catch{setError('这次没有保存成功，请再试一次。照片和录音还在。')}finally{setBusy(false)}}
 async function openHistory(target:Page='history'){try{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('sgx-elder-demo',1);r.onupgradeneeded=()=>r.result.createObjectStore('items',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});const items=await new Promise<any[]>((resolve,reject)=>{const r=db.transaction('items').objectStore('items').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});db.close();setHistory(items.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(i=>({...i,photos:i.photos.map((b:Blob)=>blobUrl(b)),voice:i.voice?blobUrl(i.voice):''})));go(target)}catch{setError('暂时无法读取，请再试一次。')}}
 const reset=()=>{delete drafts.current[kind];setPhotos([]);setWords('');setTags([]);setPeople([]);setVoice('');setWriting(false);go('fragment')}
 const ask=(text:string,voiceMessage=false)=>{if(!text.trim())return;setChat(c=>[...c,...(voiceMessage?[]:[{who:'me',text}]),{who:'ai',text:/发|亲友|日常/.test(text)?'先选一张照片，或拍下眼前的生活。说一句想说的话，再选亲友，确认后就可以发送。':/照片|存|碎片/.test(text)?'点“拾光碎片”，选择照片。您可以说说照片里有谁、在哪里；录音会和照片一起留下。':/来信|消息/.test(text)?'正式使用时，收到新来信我会轻轻提醒您，只有您点开才显示内容。现在是使用指南演示，还没有接入来信。':/录音|说话|声音/.test(text)?'点“点这里说话”开始录音，说完再点一次。听一听，满意了再保存或发送。':'您可以问我怎么存照片、录音，或给亲友发日常。我先陪您把这几件事做好。'}])}
 const back=()=>{if(busy)return;if(page==='done'){reset();return}if(recording){stop();return}go(['history','sent','contacts','settings','profile'].includes(page)?'me':page==='privacy'?'settings':page==='people'?'daily':page==='review'?(kind==='daily'?'people':'fragment'):'fragment')}
 const titles:Record<Page,string>={fragment:'拾光碎片',daily:'发日常',people:'发给谁',review:'确认内容',done:'完成',ai:'小叙',history:'已保存',me:'我的',sent:'发过的日常',contacts:'我的亲友',settings:'设置',profile:'个人资料',privacy:'账号与隐私'}
 const rootPages:Page[]=['fragment','daily','ai','me']
 const tab=page==='me'||['history','sent','contacts','settings','profile'].includes(page)?'me':page==='privacy'?'settings':page==='ai'?'ai':['daily','people'].includes(page)||(page==='review'||page==='done')&&kind==='daily'?'daily':'fragment'
 const switchTab=(target:Page)=>{if(recording||busy){setError('请先结束录音或等待保存完成。');return}if(target==='daily'||target==='fragment')start(target);else go(target)}
 return <main className={`app ${largeText?'large-text':''}`}><header>{!rootPages.includes(page)&&<button onClick={back} aria-label="返回"><ArrowLeft size={28}/></button>}{page==='ai'&&<img className="header-xiaoxu" src="./xiaoxu-helper.png" alt="小叙"/>}<b>{titles[page]}</b>{page==='me'&&<button className="account-settings" aria-label="设置" onClick={()=>go('settings')}><Gear size={27}/></button>}</header>
 {page==='me'&&<section className="account-page mini-account"><button className="profile-center" onClick={editProfile} aria-label="编辑个人资料"><img src={profile.avatar} alt={profile.name}/><h1>{profile.name}</h1><span>编辑个人资料 <CaretRight size={18}/></span></button><div className="account-menu">{([{label:'我的拾光',Icon:Images,action:()=>void openHistory()},{label:'发过的日常',Icon:PaperPlaneTilt,action:()=>void openHistory('sent')},{label:'我的亲友',Icon:UsersThree,action:()=>{go('contacts')}}]).map(({label,Icon,action})=><button key={label} onClick={action}><Icon size={28}/><span>{label}</span><CaretRight size={23}/></button>)}</div></section>}
 {page==='profile'&&<section className="profile-form"><img className="edit-avatar" src={profileAvatar} alt="我的头像"/><label className="avatar-upload">修改头像<input type="file" hidden accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/')||f.size>3*1024*1024){setError('请选择3MB以内的照片。');return}const r=new FileReader();r.onload=()=>setProfileAvatar(String(r.result));r.readAsDataURL(f)}}/></label><label>姓名<input maxLength={24} value={profileName} onChange={e=>setProfileName(e.target.value)}/></label><button className="primary" disabled={!profileName.trim()} onClick={()=>{const value={name:profileName.trim(),avatar:profileAvatar};if(persist('elder-profile',value)){setProfile(value);go('me')}}}>保存</button></section>}
 {page==='contacts'&&<section><Contacts profile={profile} onSend={id=>{start('daily');setPeople([id])}}/></section>}
 {page==='settings'&&<section><div className="account-menu"><button onClick={editProfile}><UserCircle size={28}/><span>个人资料</span><CaretRight size={23}/></button><button role="switch" aria-checked={largeText} onClick={()=>{if(persist('elder-large-text',!largeText))setLargeText(!largeText)}}><TextAa size={28}/><span>更大字号</span><i className={`setting-switch ${largeText?'on':''}`} /></button><button onClick={()=>go('privacy')}><ShieldCheck size={28}/><span>账号与隐私</span><CaretRight size={23}/></button></div></section>}
 {page==='privacy'&&<section className="privacy-copy"><h2>内容保存在这台设备</h2><p>目前未接入账号和云端服务。照片、录音、资料与称呼只保存在当前浏览器，清除浏览器数据会一起清除。</p><h2>发送与小叙</h2><p>日常暂不真实发送，小叙提供操作引导。使用浏览器语音转文字时，浏览器可能调用其语音识别服务。</p></section>}
 {(page==='fragment'||page==='daily')&&<section className="compose-simple"><h1>{kind==='fragment'?'留下这段回忆':'给亲友发个日常'}</h1><div className="upload"><button onClick={()=>picker.current?.click()}><Images size={34}/>选照片</button>{kind==='daily'&&<button onClick={()=>camera.current?.click()}><Camera size={34}/>拍一张</button>}</div><div className="photos">{photos.map(p=><div key={p.id}><img src={p.url} alt="已选照片"/><button aria-label="去掉这张照片" onClick={()=>setPhotos(v=>v.filter(x=>x.id!==p.id))}><Trash size={23}/></button></div>)}</div><p className="hint">{photos.length?`已选${photos.length}张，最多3张`:'没有照片，也可以直接说。'}</p><div className="voice-simple"><button className={`record ${recording?'recording':''}`} onClick={record}><Microphone size={32}/>{recording?'说完了，点这里':voice?'重新说一遍':'点这里说话'}</button><p className="hint">{recording?'正在录音，最多1分钟':kind==='fragment'?'说说照片里有谁，发生了什么。':'说一句想告诉他们的话。'}</p>{voice&&<div className="playback"><audio controls src={voice}/><button onClick={()=>setVoice('')}>删掉录音</button></div>}{!writing&&!words?<button className="write-link" onClick={()=>setWriting(true)}>也可以打字</button>:<label className="plain-writing"><span className="sr-only">文字内容</span><textarea aria-label="文字内容" rows={3} maxLength={500} value={words} onChange={e=>setWords(e.target.value)} placeholder="写下想说的话"/></label>}</div>{kind==='fragment'&&tags.length>0&&<div className="recognized-tags"><p className="hint">标签 · 点一下可去掉</p><div className="tags">{tags.map(t=><button key={t} onClick={()=>setTags(v=>v.filter(x=>x!==t))}>{t} ×</button>)}</div></div>}<button className="primary" disabled={busy||recording||(!photos.length&&!voice&&!words.trim())} onClick={()=>kind==='daily'?go('people'):void save()}>{busy?'正在保存…':kind==='daily'?'下一步，发给谁':'保存'}{kind==='daily'&&<ArrowRight size={25}/>}</button><input hidden ref={picker} type="file" accept="image/*" multiple onChange={e=>{upload(e.target.files);e.target.value=''}}/><input hidden ref={camera} type="file" accept="image/*" capture="environment" onChange={e=>{upload(e.target.files);e.target.value=''}}/></section>}
 {page==='people'&&<section><h1>想让谁看看？</h1><p>可以选一位，也可以多选。</p>{ACCOUNTS.map((person,i)=><button className={`person ${people.includes(person.id)?'selected':''}`} key={person.id} onClick={()=>toggle(person.id,people,setPeople)}><span className={'avatar a'+i}>{person.initial}</span><b>{person.name}<small className="recipient-relation">{person.relation}</small></b><span className="tick">{people.includes(person.id)?<Check size={25}/>:null}</span></button>)}<button className="primary" disabled={!people.length} onClick={()=>go('review')}>选好了，看看内容<ArrowRight size={25}/></button></section>}
 {page==='review'&&<section><div className="step">{kind==='daily'?'确认发送':'确认保存'}</div><h1>{kind==='daily'?'这份日常，发给他们。':'把这段时光留下。'}</h1>{kind==='daily'&&<div className="recipients">发给：{people.map(id=>ACCOUNTS.find(a=>a.id===id)?.name||id).join('、')}</div>}<div className="preview">{photos.map(p=><img key={p.id} src={p.url} alt="照片预览"/>)}{words&&<p>{words}</p>}{voice&&<audio controls src={voice}/>}<div className="tags">{tags.map(t=><span key={t}>{t}</span>)}</div></div><p className="hint">{kind==='daily'?'体验版只保存发送记录，不会真正发出。':'保存在当前浏览器，暂未同步到相框。'}</p><button className="primary" disabled={busy} onClick={save}>{busy?'正在保存…':kind==='daily'?'确认发送（演示）':'保存这段时光'}</button><button className="secondary" disabled={busy} onClick={()=>go(kind)}>回去改一改</button></section>}
 {page==='done'&&<section className="success"><div className="success-icon"><Check size={48}/></div><h1>{kind==='daily'?'这份日常准备好了':'这段时光已保存'}</h1><p>{kind==='daily'?'已在本机保存演示记录，还没有真正发给亲友。':'照片、录音和文字已留在这台设备上。'}</p><button className="primary" onClick={reset}>完成</button></section>}
 {(page==='history'||page==='sent')&&<section><h1>{page==='sent'?'发过的日常':'我的拾光'}</h1><p className="hint">仅保存在当前浏览器。清除浏览器数据后，这些内容也会清除。</p>{!history.some(item=>item.kind===(page==='sent'?'daily':'fragment'))&&<p>还没有留下内容。选一张照片，或说几句话试试吧。</p>}{history.filter(item=>item.kind===(page==='sent'?'daily':'fragment')).map(item=><article className="preview" key={item.id}><h2>{item.kind==='daily'?'日常 · 演示记录':'拾光碎片'}</h2><p className="hint">{new Date(item.createdAt).toLocaleString('zh-CN')}</p>{item.kind==='daily'&&<p>收件人：{item.people.join('、')}（未实际发送）</p>}{item.photos.map((url:string,i:number)=><img src={url} key={i} alt="保存的照片"/>)}{item.words&&<p>{item.words}</p>}{item.voice&&<audio controls src={item.voice}/>}<div className="tags">{item.tags.map((tag:string)=><span key={tag}>{tag}</span>)}</div></article>)}</section>}
 {page==='ai'&&<section className="chat"><p className="demo">小叙使用指南 · 当前为引导演示，未接通AI服务</p><div className="messages">{chat.map((m,i)=><div className={`message ${m.who}`} key={i}>{m.who==='ai'&&<img src="./xiaoxu-helper.png" alt="小叙"/>}<div className="chat-bubble">{m.audio&&<audio controls src={m.audio} aria-label="我的语音"/>}{m.text&&<p>{m.text}</p>}</div></div>)}</div><div className="quick">{['怎么存照片？','怎么发给亲友？'].map(t=><button key={t} onClick={()=>ask(t)}>{t}</button>)}</div><ChatComposer onText={ask} onVoice={(blob,text)=>{const audio=blobUrl(blob);setChat(c=>[...c,{who:'me',text,audio}]);if(text)ask(text,true);else setChat(c=>[...c,{who:'ai',text:'语音已留下，但这次没有识别出文字。您可以打字，或点上面的常用问题。'}])}}/></section>}
 <nav className="bottom-tabs" aria-label="主要导航">{([{page:'fragment',label:'拾光碎片',Icon:Images},{page:'daily',label:'发日常',Icon:PaperPlaneTilt},{page:'ai',label:'小叙',Icon:Images},{page:'me',label:'我的',Icon:UserCircle}] as const).map(t=><button key={t.page} className={tab===t.page?'active':''} aria-current={tab===t.page?'page':undefined} onClick={()=>switchTab(t.page)}>{t.page==='ai'?<img className="tab-xiaoxu" src="./xiaoxu-helper.png" alt=""/>:<t.Icon size={29} weight={tab===t.page?'fill':'regular'}/>}<span>{t.label}</span></button>)}</nav>
 {error&&<p role="alert" className="error">{error}</p>}
 </main>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
