import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, BookOpen, CaretLeft, CaretRight, EnvelopeOpen, FrameCorners, GearSix, Heart, House, Images, Pause, PencilLine, Play, SpeakerHigh, UsersThree, X } from '@phosphor-icons/react'
import { bundled, caseId, readGift, validGift, type Block } from './data'
import { Photo, Voice } from './media'
import './retirement.css'
const tabs=[['home','相框',House],['photos','时光相册',Images],['stories','记得的故事',BookOpen],['wishes','大家的心意',Heart],['letter','一封信',EnvelopeOpen],['received','新问候',UsersThree]] as const
function route() {const path=location.hash.replace(/^#/, '').split('?')[0].split('/').filter(Boolean);const key=path[1]||'home';return ({family:'wishes',fragments:'photos',river:'photos',study:'stories',interaction:'received',conversation:'received',album:'photos',memoir:'stories',diary:'diary',ai:'ai',settings:'settings'} as Record<string,string>)[key] || (['home','photos','stories','wishes','letter','received'].includes(key)?key:'home')}
function stored<T,>(key:string,fallback:T):T {try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}
export default function RetirementFrame() {
  const [id,setId]=useState(caseId);const [gift,setGift]=useState(()=>readGift(id));const [page,setPage]=useState(route)
  const [slide,setSlide]=useState(0);const [playing,setPlaying]=useState(false);const [detail,setDetail]=useState<Block|null>(null)
  const [collapsed,setCollapsed]=useState(false);const [greet,setGreet]=useState(true);const [speech,setSpeech]=useState(false);const [notice,setNotice]=useState('')
  const [size,setSize]=useState(()=>stored('sgx-frame-font','normal'));const [interval,setIntervalSec]=useState(()=>stored('sgx-frame-interval',8));
  const [reply,setReply]=useState('');const [replies,setReplies]=useState<Record<string,string>>(()=>stored(`sgx-frame-replies:${id}`,{}))
  const [diary,setDiary]=useState('');const [entries,setEntries]=useState<{id:string;text:string;date:string}[]>(()=>stored(`sgx-frame-diary:${id}`,[]))
  const [selectedPhoto,setSelectedPhoto]=useState<string|null>(null); const main=useRef<HTMLElement>(null)
  const stop=()=>{window.speechSynthesis?.cancel();setSpeech(false);document.querySelectorAll('audio').forEach(a=>a.pause())}
  function go(next:string){ stop();setDetail(null);setSelectedPhoto(null);setReply('');setPlaying(false);const params=new URLSearchParams(location.hash.split('?')[1]);params.set('case',id);params.set('scenario','teacher-retirement');location.hash=`/frame${next==='home'?'':'/'+next}?${params}` }
  useEffect(()=>{const update=()=>{const next=caseId();setId(next);setGift(readGift(next));setPage(route());setDetail(null);setSlide(0);stop();main.current?.scrollTo(0,0)};const message=(e:MessageEvent)=>{if(e.origin!==location.origin||e.source!==window.parent||e.data?.type!=='sgx:frame-gift'||!validGift(e.data.gift,caseId()))return;setGift(e.data.gift)};const storage=(e:StorageEvent)=>{if(e.key===`sgx-frame-gift-v1:${caseId()}`)setGift(readGift(caseId()))};window.addEventListener('hashchange',update);window.addEventListener('message',message);window.addEventListener('storage',storage);if(window.parent!==window)window.parent.postMessage({type:'sgx:frame-ready'},location.origin);return()=>{window.removeEventListener('hashchange',update);window.removeEventListener('message',message);window.removeEventListener('storage',storage);stop()}},[])
  useEffect(()=>{setReplies(stored(`sgx-frame-replies:${id}`,{}));setEntries(stored(`sgx-frame-diary:${id}`,[]));setDiary('')},[id])
  useEffect(()=>{const t=setTimeout(()=>setGreet(false),7000);return()=>clearTimeout(t)},[])
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(t)},[notice])
  useEffect(()=>{if(!detail&&!selectedPhoto)return;const previous=document.activeElement as HTMLElement|null;const dialog=document.querySelector<HTMLElement>('.rf-dialog');const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){stop();setDetail(null);setSelectedPhoto(null)}if(e.key==='Tab'&&dialog){const items=Array.from(dialog.querySelectorAll<HTMLElement>('button:not(:disabled),textarea,a[href],audio'));const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};window.addEventListener('keydown',key);return()=>{window.removeEventListener('keydown',key);previous?.focus()}},[detail,selectedPhoto])
  const photos=gift.photos;const stories=gift.blocks.filter(b=>b.kind==='story');const wishes=gift.blocks.filter(b=>b.kind==='wish');const author=(authorId:string)=>gift.blocks.find(b=>b.authorId===authorId)?.author||'共创者'
  // Group only adjacent photographs from the same period; preserve the curator's order.
  const shots=useMemo(()=>{const groups:typeof photos[]=[];photos.forEach(p=>{const last=groups[groups.length-1];if(p.date&&last&&last.length<4&&last[0].date.slice(0,4)===p.date.slice(0,4))last.push(p);else groups.push([p])});return groups},[photos])
  const shot=shots[slide%Math.max(shots.length,1)]||[]
  useEffect(()=>{if(!playing||shots.length<2)return;const t=setTimeout(()=>setSlide(x=>(x+1)%shots.length),interval*1000);return()=>clearTimeout(t)},[playing,slide,shots.length,interval])
  useEffect(()=>{const hidden=()=>{if(document.hidden){setPlaying(false);stop()}};document.addEventListener('visibilitychange',hidden);return()=>document.removeEventListener('visibilitychange',hidden)},[])
  function read(text:string){if(!('speechSynthesis'in window)){setNotice('此设备暂不支持朗读，可以直接阅读。');return}if(speech){stop();return}stop();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='zh-CN';utterance.rate=.85;utterance.onend=()=>setSpeech(false);utterance.onerror=()=>{setSpeech(false);setNotice('朗读暂不可用，请检查设备的中文语音。')};speechSynthesis.speak(utterance);setSpeech(true)}
  function respond(b:Block,text:string){const next={...replies,[b.id]:text};try{localStorage.setItem(`sgx-frame-replies:${id}`,JSON.stringify(next));setReplies(next);setReply('');setNotice('回应已保存在本机演示中')}catch{setNotice('本机空间不足，回应尚未保存')}}
  const detailPhoto=selectedPhoto?gift.media.find(p=>p.id===selectedPhoto):null
  const frame = <div className={`rf-slides count-${shot.length}`} key={`${id}-${slide}`}>
    {shot.map(p=><button key={p.id} onClick={()=>{setSelectedPhoto(p.id);setPlaying(false)}} aria-label={`查看照片：${p.caption}`}><Photo path={p.path} alt={p.caption}/><span>{p.caption}<small>{author(p.authorId)} · {p.date||'时间未记下'}</small></span></button>)}
    {!shot.length&&<div className="rf-empty">大家的照片，会在这里慢慢展开。</div>}
  </div>
  const controls=<div className="rf-playback"><button aria-label="上一组照片" disabled={shots.length<2} onClick={()=>{setSlide(x=>(x-1+shots.length)%shots.length);setPlaying(false)}}><CaretLeft/></button><button onClick={()=>setPlaying(!playing)} disabled={!photos.length}>{playing?<Pause/>:<Play/>}{playing?'暂停轮播':'播放回忆'}</button><span>{shots.length?slide%shots.length+1:0} / {shots.length}</span><button aria-label="下一组照片" disabled={shots.length<2} onClick={()=>{setSlide(x=>(x+1)%shots.length);setPlaying(false)}}><CaretRight/></button></div>
  const readButton=(text:string)=><button className="rf-soft" onClick={()=>read(text)}><SpeakerHigh/>{speech?'停止朗读':'读给我听'}</button>
  const showBlock=(b:Block)=><button className="rf-content-card" key={b.id} onClick={()=>{setDetail(b);setReply('')}}>{b.photoIds[0]&&gift.media.find(p=>p.id===b.photoIds[0])&&<Photo path={gift.media.find(p=>p.id===b.photoIds[0])!.path} alt={b.title}/>}<small>{b.author} · {b.relation}</small><h3>{b.title||`来自${b.author}的心意`}</h3><p>{b.body}</p><span className="rf-card-link">{b.audio?'听听这份心意':'慢慢读'} <ArrowRight size={19}/></span>{replies[b.id]&&<em>你已回应</em>}</button>
  return <div className={`retirement-frame rf-size-${size} ${collapsed?'rf-companion-hidden':''}`}>
    <header className="rf-header"><button className="rf-brand" onClick={()=>go('home')}><FrameCorners size={30}/><span>拾光叙</span></button><span className="rf-owner">{gift.address}的时光</span><button aria-label="相框设置" onClick={()=>go('settings')}><GearSix size={26}/></button></header>
    <div className="rf-layout"><main className={`rf-main rf-main--${page}`} ref={main}>
      {page==='home'&&<><div className="rf-heading"><div><small>{gift.host} · {gift.category}</small><h1>那些被记得的时光，<br/>都在这里。</h1></div><span className="rf-date">{gift.date.split('-').join(' · ')}</span></div>{frame}{controls}<div className="rf-home-links"><button onClick={()=>go('stories')}><BookOpen/><span>记得的故事<small>{stories.length}段记忆，慢慢读</small></span><ArrowRight/></button><button onClick={()=>go('letter')}><EnvelopeOpen/><span>大家写给你的一封信<small>把许多人的谢谢，说给你听</small></span><ArrowRight/></button></div></>}
      {page==='photos'&&<><div className="rf-heading"><div><small>时光相册 · {photos.length}张</small><h1>每一张，都有人记得。</h1></div></div>{frame}{controls}<div className="rf-photo-grid">{photos.map(p=><button key={p.id} onClick={()=>{setSelectedPhoto(p.id);setPlaying(false)}}><Photo path={p.path} alt={p.caption}/><span>{p.caption}</span><small>{p.date||'时间未记下'} · {author(p.authorId)}</small></button>)}</div></>}
      {page==='stories'&&<><div className="rf-heading"><div><small>记得的故事 · {stories.length}篇</small><h1>有些事，没有被忘记。</h1></div><button className="rf-soft" onClick={()=>go('diary')}><PencilLine/>我也记一段</button></div><div className="rf-cards">{stories.map(showBlock)}</div>{!stories.length&&<p className="rf-empty">还没有收录故事。</p>}</>}
      {page==='wishes'&&<><div className="rf-heading"><div><small>{new Set(wishes.map(b=>b.authorId)).size}个人的心意</small><h1>想对您说的话，<br/>都带来了。</h1></div></div><div className="rf-cards rf-wish-cards">{wishes.map(showBlock)}</div>{!wishes.length&&<p className="rf-empty">还没有收录祝福。</p>}</>}
      {page==='letter'&&<><div className="rf-heading"><div><small>AI 小叙协助整理 · {gift.letterConfirmed?'已确认':'待统筹者确认'}</small><h1>大家写给你的一封信</h1></div>{gift.letter&&readButton(gift.letter)}</div><article className="rf-letter"><EnvelopeOpen size={34}/>{gift.letter?<div>{gift.letter}</div>:<p>这封信还在整理中。统筹者确认后，会和大家的心意一起来到这里。</p>}<footer>{gift.host} · {gift.date}</footer></article></>}
      {page==='received'&&<><div className="rf-heading"><div><small>新问候 · {gift.fresh.length}份</small><h1>相聚以后，<br/>依然有人惦记。</h1></div></div><div className="rf-cards">{gift.fresh.map(showBlock)}</div>{!gift.fresh.length&&<div className="rf-empty"><EnvelopeOpen size={44}/><h3>新的问候，会来到这里。</h3><p>亲友后来发来的照片、文字和声音，都可以在这里打开并回应。</p><button className="rf-primary" onClick={()=>go('wishes')}>先看看大家的祝福</button></div>}</>}
      {page==='settings'&&<><div className="rf-heading"><div><small>相框设置</small><h1>按习惯，慢慢看。</h1></div></div><div className="rf-settings"><section><h3>文字大小</h3><div className="rf-options">{[['normal','舒适'],['large','更大']].map(([v,label])=><button aria-pressed={size===v} key={v} onClick={()=>{setSize(v);localStorage.setItem('sgx-frame-font',JSON.stringify(v))}}>{label}</button>)}</div></section><section><h3>照片轮播</h3><div className="rf-options">{[6,8,12].map(v=><button key={v} aria-pressed={interval===v} onClick={()=>{setIntervalSec(v);localStorage.setItem('sgx-frame-interval',JSON.stringify(v))}}>{v}秒 / 组</button>)}</div></section><section><h3>这份礼物</h3><p>{gift.address} · {gift.category}</p><p>{gift.host} · {gift.date}</p><small>{gift.preview?'正在查看整理预览':`仪式版本 ${gift.version || 1}`}</small></section></div></>}
      {(page==='ai'||page==='diary')&&<><div className="rf-heading"><div><small>AI 小叙 · 陪你慢慢记</small><h1>您记得的那一刻，<br/>也可以留下来。</h1></div></div><div className="rf-journal"><p className="rf-prompt">{gift.address}，大家写下了这么多记忆。看到这些照片，您最想起哪一件小事？</p><textarea aria-label="我的回忆" value={diary} onChange={e=>setDiary(e.target.value)} maxLength={2000} placeholder="从一个画面、一个人，或者一句话开始……"/><div className="rf-options"><button onClick={()=>go('photos')}>看看照片，找点灵感</button><button className="rf-primary" disabled={!diary.trim()} onClick={()=>{const next=[{id:crypto.randomUUID(),text:diary.trim(),date:new Date().toLocaleDateString('zh-CN')},...entries];try{localStorage.setItem(`sgx-frame-diary:${id}`,JSON.stringify(next));setEntries(next);setDiary('');setNotice('这段回忆已保存在本机')}catch{setNotice('本机空间不足，尚未保存')}}}>留下这段回忆</button></div><small>这里记录在当前设备，不会自动发给其他人。</small>{entries.map(e=><article key={e.id}><small>{e.date}</small><p>{e.text}</p>{readButton(e.text)}</article>)}</div></>}
    </main><aside className="rf-companion" aria-label="小叙陪伴"><button className="rf-collapse" aria-label={collapsed?'展开小叙':'收起小叙'} onClick={()=>setCollapsed(!collapsed)}>{collapsed?<CaretLeft/>:<CaretRight/>}</button>{!collapsed&&<><div className={`rf-greeting ${greet?'is-greeting':''}`}><strong>嗨，{gift.address}。</strong><p>{greet?'我是小叙，陪您慢慢看。':'想听一封信，还是聊聊往事？'}</p></div><button className="rf-mascot" onClick={()=>{setGreet(true);go('ai')}} aria-label="和小叙记一段回忆"><img src={bundled('xiaoxu-perch.png')} alt="小叙扶着相框边缘探头"/></button><button className="rf-companion-action" onClick={()=>go('ai')}>和小叙记一段</button><button className="rf-companion-action" onClick={()=>go('letter')}>读一封信</button></>}</aside></div>
    <nav className="rf-nav" aria-label="相框导航">{tabs.map(([key,label,Icon])=><button key={key} aria-current={page===key?'page':undefined} onClick={()=>go(key)}><Icon size={25} weight={page===key?'duotone':'regular'}/><span>{label}</span>{key==='received'&&gift.fresh.length>0&&<i>{gift.fresh.length}</i>}</button>)}</nav>
    {(detail||detailPhoto)&&<div className="rf-overlay" onClick={()=>{stop();setDetail(null);setSelectedPhoto(null)}}><section className="rf-dialog" role="dialog" aria-modal="true" aria-label={detail?.title||detailPhoto?.caption||'这份心意'} onClick={e=>e.stopPropagation()}><button className="rf-dialog-close" aria-label="关闭详情" autoFocus onClick={()=>{stop();setDetail(null);setSelectedPhoto(null)}}><X/></button>{detailPhoto?<><Photo path={detailPhoto.path} alt={detailPhoto.caption}/><h2>{detailPhoto.caption}</h2><p>{author(detailPhoto.authorId)} · {detailPhoto.date||'时间未记下'}</p>{readButton(detailPhoto.caption)}</>:detail&&<><small>{detail.author} · {detail.relation}</small><h2>{detail.title||'有句话，想对您说'}</h2>{detail.photoIds.map(photoId=>{const p=gift.media.find(x=>x.id===photoId);return p?<Photo key={p.id} path={p.path} alt={p.caption}/>:null})}<p className="rf-full-text">{detail.body}</p>{detail.sticker&&<Photo path={`images/sticker-${detail.sticker}.png`} alt="送来的祝福表情" className="rf-sticker"/>}{detail.audio?<Voice path={detail.audio} text={detail.audioText}/>:readButton(detail.body)}<div className="rf-reply"><h3>也回应一下这份心意</h3>{replies[detail.id]&&<p className="rf-saved">我的回应：{replies[detail.id]}</p>}<div className="rf-options">{['谢谢你，我都记得','看到了，心里很暖'].map(text=><button key={text} onClick={()=>respond(detail,text)}>{text}</button>)}</div><label>也可以说一句<textarea value={reply} onChange={e=>setReply(e.target.value)} maxLength={300} placeholder={`想对${detail.author}说……`}/></label><button className="rf-primary" disabled={!reply.trim()} onClick={()=>respond(detail,reply.trim())}>留下回应</button><small>演示回应保存在当前设备。</small></div></>}</section></div>}
    {notice&&<div role="status" className="rf-notice">{notice}</div>}
    {page!=='home'&&<button className="rf-back" onClick={()=>go('home')}><ArrowLeft size={18}/>回到相框</button>}
  </div>
}
