import { test, expect, type Page } from '@playwright/test'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

const key = 'shiguangxu-rongxiu-demo-v1'
const chapter = (page: Page, text: string) =>
  page.getByRole('navigation', { name: '演示章节' }).getByRole('button', { name: text })
const state = (page: Page) => page.evaluate((k) => JSON.parse(localStorage.getItem(k)!), key)

test('老师主线：用途确认、无主创定稿、同码现场、节日心意与接收回执', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (e) => errors.push(e.message))
  await page.goto('/')
  await page.getByRole('button', { name: '我来参与共创', exact: false }).click()
  await page.getByRole('button', { name: '我来留一份心意', exact: true }).click()
  await page.getByRole('button', { name: '开始共创', exact: true }).click()
  await page
    .getByRole('textbox', { name: '共创内容', exact: true })
    .fill('陈老师，您教会我们耐心看待自己的进步。这个下午，一直记得。')
  await page.getByRole('button', { name: '预览这份心意', exact: true }).click()
  await page.getByRole('button', { name: '确认提交', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('请先确认')
  await page.getByRole('checkbox', { name: '送给陈老师，用于这次荣休礼' }).check()
  await page.getByRole('checkbox', { name: '同意在本次荣休仪式上展示' }).check()
  await page.getByRole('button', { name: '确认提交', exact: true }).click()
  await expect(page.getByRole('switch', { name: '设置主创', exact: true })).not.toBeChecked()
  await page.getByRole('button', { name: '以后教师节，也想问候陈老师？', exact: false }).click()
  await page.getByRole('button', { name: '查看自动整理的礼物', exact: false }).click()
  const frozen = (await state(page)).cases.teacher.frozen
  expect(frozen.body).toContain('这个下午，一直记得')
  await page.getByRole('button', { name: '仪式：一段回忆', exact: true }).click()
  await expect(page.locator('.ritual-story')).toContainText('这个下午，一直记得')
  await page.locator('.journey-footer').getByRole('button', { name: '下一步' }).click()
  await expect(page.getByRole('switch', { name: '开启现场专用码' })).not.toBeChecked()
  await page.getByRole('button', { name: '留住今天', exact: false }).click()
  await expect(page.getByRole('button', { name: '现场心意已提交', exact: false })).toBeVisible()
  await page.locator('.journey-footer').getByRole('button', { name: '下一步' }).click()
  await expect(page.locator('.person-card')).toHaveCount(3)
  await page.locator('.journey-footer').getByRole('button', { name: '下一步' }).click()
  await page.getByRole('button', { name: '查看并送上心意', exact: false }).click()
  await expect(page.locator('.remember-card')).toContainText('这个下午，一直记得')
  await page.getByRole('button', { name: '写祝福 / 发照片', exact: false }).click()
  await page
    .getByRole('textbox', { name: '节日祝福' })
    .fill('教师节快乐，陈老师！今天也有新故事想告诉您。')
  await page.getByRole('button', { name: '加一张今天的照片', exact: false }).click()
  await page.getByRole('button', { name: '路过的风景 · 校园树荫', exact: false }).click()
  await page.getByRole('button', { name: '送给陈老师', exact: true }).click()
  await expect(page.locator('.success-heading')).toContainText('心意已提交')
  expect((await state(page)).cases.teacher.delivery).toBe('processing')
  await page.getByRole('button', { name: '看看相框收到', exact: false }).click()
  await expect(page.locator('.received-letter')).toContainText('今天也有新故事')
  await page.getByRole('button', { name: '模拟暂未接收', exact: true }).click()
  await expect(page.locator('.receipt-badge')).toContainText('等待接收回执')
  await page.getByRole('button', { name: '模拟相框接收', exact: false }).click()
  await expect(page.locator('.receipt-badge')).toContainText('相框已接收')
  expect((await state(page)).cases.teacher.frozen).toEqual(frozen)
  await page.reload()
  await expect(page.locator('.receipt-badge')).toContainText('相框已接收')
  expect(errors).toEqual([])
})

test('无外部渠道与未开启提醒不制造通知，设置按人物隔离', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '我来参与共创', exact: false }).click()
  await chapter(page, '重要日子，再问候').click()
  await expect(page.getByRole('button', { name: '开启教师节提醒', exact: true })).toBeVisible()
  await expect(page.locator('.notification')).toHaveCount(0)
  await page.getByRole('button', { name: '开启教师节提醒', exact: true }).click()
  await page.getByRole('button', { name: '服务号示意', exact: true }).click()
  await expect(page.getByRole('heading', { name: '服务号渠道尚未关联' })).toBeVisible()
  await page.getByRole('button', { name: '演示渠道可用状态', exact: true }).click()
  await expect(page.locator('.notification')).toHaveClass(/wechat/)
  await page.getByRole('button', { name: '查看并送上心意', exact: false }).click()
  await page.getByRole('button', { name: '今天先不提醒我', exact: true }).click()
  let data = await state(page)
  expect(data.cases.teacher.skipped).toBe(true)
  expect(data.cases.teacher.eventEnabled).toBe(true)
  expect(data.cases.leader.eventEnabled).toBe(false)
  await page.getByRole('button', { name: '管理这个人的提醒', exact: false }).click()
  await page.getByRole('switch', { name: '陈老师教师节提醒' }).click()
  await page.getByRole('button', { name: '完成设置', exact: false }).click()
  await expect(page.locator('.notification')).toHaveCount(0)
  data = await state(page)
  expect(data.cases.teacher.eventEnabled).toBe(false)
})

test('案例切换、私下赠礼、版本不可变与单案例重置', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '我来参与共创', exact: false }).click()
  await page.locator('.case-switch').click()
  await page.locator('.case-card').filter({ hasText: '周启山' }).click()
  await expect(page.locator('.hero-copy')).toContainText('周启山')
  await chapter(page, '确认这份心意').click()
  await page.getByRole('checkbox', { name: '送给周老师，用于这次荣休礼' }).check()
  await page.getByRole('button', { name: '确认提交', exact: true }).click()
  await expect(page.getByRole('switch', { name: '设置主创', exact: true })).toBeChecked()
  await page.getByRole('button', { name: '演示主创确认定稿', exact: false }).click()
  expect((await state(page)).cases.leader.frozen.included).toBe(false)
  await page.getByRole('button', { name: '仪式：一段回忆', exact: true }).click()
  await expect(page.locator('.ritual-story')).not.toContainText('第一次独立带项目')
  await chapter(page, '重要日子，再问候').click()
  await expect(page.getByRole('button', { name: '开启生日提醒', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '开启生日提醒', exact: true }).click()
  await page.locator('.case-switch').click()
  await page.locator('.case-card').filter({ hasText: '沈知秋' }).click()
  await chapter(page, '重要日子，再问候').click()
  await expect(page.getByRole('button', { name: '开启护士节提醒', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '开启护士节提醒', exact: true }).click()
  await page.getByRole('button', { name: '重新演示', exact: true }).click()
  await page.getByRole('button', { name: '重新开始这个案例', exact: false }).click()
  const data = await state(page)
  expect(data.cases.nurse.eventEnabled).toBe(false)
  expect(data.cases.leader.eventEnabled).toBe(true)
  expect(data.step).toBe(0)
})

test('手机375宽不横向溢出，目录和底部下一步可操作', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto('/')
  await page.getByRole('button', { name: '我来参与共创', exact: false }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: '打开章节目录' }).click()
  await chapter(page, '走进荣休仪式').click()
  await expect(page.locator('.frame-device')).toBeVisible()
  await page.getByRole('button', { name: '仪式：下一程', exact: true }).click()
  await expect(page.locator('.ritual-ending')).toContainText('有时间慢慢做喜欢的事')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.locator('.journey-footer').getByRole('button', { name: '下一步' }).click()
  await expect(page.getByRole('textbox', { name: '现场祝福' })).toBeVisible()
})

test('再次问候保留上一份内容，人物历史和提醒行动状态连续', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '我来参与共创', exact: false }).click()
  await chapter(page, '再送一份心意').click()
  await page.getByRole('textbox', { name: '节日祝福' }).fill('第一份祝福：祝陈老师教师节快乐。')
  await page.getByRole('button', { name: '送给陈老师', exact: true }).click()
  await page.getByRole('button', { name: '还想说点什么？再补一份心意', exact: false }).click()
  await expect(page.getByRole('textbox', { name: '节日祝福' })).toHaveValue('')
  let data = await state(page)
  expect(data.cases.teacher.greetingHistory).toHaveLength(1)
  expect(data.cases.teacher.greetingHistory[0].body).toContain('第一份祝福')
  await page
    .getByRole('textbox', { name: '节日祝福' })
    .fill('第二份心意：还有一段今天的近况想告诉您。')
  await page.getByRole('button', { name: '送给陈老师', exact: true }).click()
  await chapter(page, '我参与过的人').click()
  await page.locator('.person-card.featured').click()
  await expect(page.locator('.section-heading')).toContainText('4 份')
  await page.locator('.history-item').filter({ hasText: '第一份祝福' }).click()
  await expect(page.getByRole('dialog')).toContainText('第一份祝福')
  await expect(page.getByRole('dialog')).not.toContainText('第二份心意')
  await page.getByRole('button', { name: '关闭弹窗', exact: true }).click()
  await chapter(page, '重要日子，再问候').click()
  await page.getByRole('button', { name: '开启教师节提醒', exact: true }).click()
  await expect(page.locator('.notification')).toContainText('你已送出教师节心意')
  data = await state(page)
  expect(data.cases.teacher.greetingHistory).toHaveLength(1)
})

test('离线单文件断网可打开，照片、编辑与案例切换无需外部资源', async ({ page, context }) => {
  const errors: string[] = []
  const external: string[] = []
  page.on('pageerror', (e) => errors.push(e.message))
  page.on('request', (r) => {
    if (/^https?:/.test(r.url())) external.push(r.url())
  })
  await context.setOffline(true)
  await page.goto(pathToFileURL(resolve('presentation/拾光叙-荣休礼互动演示.html')).href)
  await page.getByRole('button', { name: '我来参与共创', exact: false }).click()
  await expect(page.getByRole('heading', { level: 1 })).toContainText('送给陈老师')
  await expect
    .poll(() =>
      page.locator('.invitation-hero img').evaluate((img: HTMLImageElement) => img.naturalWidth),
    )
    .toBeGreaterThan(0)
  await page.locator('.journey-footer').getByRole('button', { name: '下一步' }).click()
  await page.getByRole('textbox', { name: '共创内容', exact: true }).fill('离线也能编辑和浏览。')
  await page.reload()
  await expect(page.getByRole('textbox', { name: '共创内容', exact: true })).toHaveValue(
    '离线也能编辑和浏览。',
  )
  await page.locator('.case-switch').click()
  await page.locator('.case-card').filter({ hasText: '沈知秋' }).click()
  await expect
    .poll(() =>
      page.locator('.invitation-hero img').evaluate((img: HTMLImageElement) => img.naturalWidth),
    )
    .toBeGreaterThan(0)
  expect(errors).toEqual([])
  await chapter(page, '留下我的回忆').click()
  await page.getByRole('button', { name: '送祝福', exact: true }).click()
  await page.getByRole('button', { name: '选择谢谢表情', exact: true }).click()
  await expect
    .poll(() =>
      page
        .locator('.sticker-grid img')
        .first()
        .evaluate((img: HTMLImageElement) => img.naturalWidth),
    )
    .toBeGreaterThan(0)
  await page.getByRole('button', { name: '用声音', exact: true }).click()
  await page.getByRole('button', { name: '开始语音演示', exact: true }).click()
  await page.getByRole('button', { name: '结束语音演示', exact: true }).click()
  await expect
    .poll(() => page.locator('audio').evaluate((el: HTMLAudioElement) => el.duration))
    .toBeGreaterThan(1)
  expect(external).toEqual([])
})

test('个人中心跨人物管理、单独关系修改、个人资料与删除持久化', async ({ page }) => {
  await page.goto('/')
  await chapter(page, '我参与过的人').click()
  await page.getByRole('button', { name: '我的', exact: true }).click()
  await page.getByRole('button', { name: '我与参与过的人的关系', exact: true }).click()
  await expect(page.locator('.relation-card')).toHaveCount(3)
  const leader = page.locator('.relation-card').filter({ hasText: '周启山' })
  await leader.getByRole('button', { name: '调整关系' }).click()
  await page.getByLabel('我与周启山的关系').fill('一起工作十年的同事')
  await page.getByRole('button', { name: '保存这段关系' }).click()
  expect((await state(page)).cases.leader.relation).toBe('一起工作十年的同事')
  expect((await state(page)).cases.teacher.relation).not.toBe('一起工作十年的同事')
  await page.getByRole('button', { name: '返回我的' }).click()
  await page.getByRole('button', { name: '个人信息', exact: true }).click()
  await page.getByLabel('昵称／默认署名').fill('林小悦')
  await page.getByRole('button', { name: '保存个人信息' }).click()
  expect((await state(page)).profile.name).toBe('林小悦')
  await page.getByRole('button', { name: '返回我的' }).click()
  await page.getByRole('button', { name: '我的共创记录', exact: true }).click()
  await expect(page.locator('.record-row')).toHaveCount(4)
  await expect(page.locator('.record-row').filter({ hasText: '陈明远' })).toHaveCount(2)
  await expect(page.locator('.record-row').filter({ hasText: '周启山' })).toHaveCount(1)
  await expect(page.locator('.record-row').filter({ hasText: '沈知秋' })).toHaveCount(1)
  await page.locator('.record-row').filter({ hasText: '周启山' }).getByRole('checkbox').check()
  await page.getByRole('button', { name: '删除选中的 1 条记录' }).click()
  await page.getByRole('button', { name: '确认删除', exact: true }).click()
  await expect(page.locator('.record-row')).toHaveCount(3)
  await page.reload()
  expect((await state(page)).cases.leader.deletedRecords).toContain('memory')
  expect((await state(page)).profile.name).toBe('林小悦')
})

test('单位主办资料、校徽与人物介绍进入邀请和相框', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '我想为别人发起', exact: false }).click()
  await expect(page.getByLabel('主办单位名称')).toHaveValue('清华大学')
  await page
    .locator('.host-form')
    .getByRole('button', { name: '下一步 · 人物资料', exact: false })
    .click()
  await page.getByLabel('给共创者看的简介').fill('陈老师陪伴我们走过一段难忘的大学时光。')
  await page.getByRole('button', { name: '保存并预览共创邀请', exact: false }).click()
  await expect(page.locator('.recipient-basics')).toContainText('难忘的大学时光')
  await expect(page.locator('.host-badge')).toContainText('清华大学')
  await expect
    .poll(() =>
      page.locator('.host-logo img').evaluate((img: HTMLImageElement) => img.naturalWidth),
    )
    .toBeGreaterThan(0)
  await chapter(page, '走进荣休仪式').click()
  await expect(page.locator('.ritual-opening .host-badge')).toContainText('清华大学')
  await page.screenshot({ path: '../../output/rongxiu-v2-organizer.png', fullPage: true })
})

test('为自己发起生日采用本人资料和公开邀请，可不设主创', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '我想为自己发起', exact: false }).click()
  await expect(page.getByLabel('你在活动中的角色')).toHaveValue('本人')
  await expect(page.getByLabel('活动类型')).toHaveValue('birthday')
  await page
    .locator('.host-form')
    .getByRole('button', { name: '下一步 · 人物资料', exact: false })
    .click()
  await expect(page.getByLabel('邀请页上的称呼')).toHaveValue('林悦')
  await expect(page.getByLabel('惊喜筹备，受礼者暂不参与收集')).toBeDisabled()
  await page.getByRole('button', { name: '保存并预览共创邀请', exact: false }).click()
  await expect(page.locator('.hero-copy')).toContainText('生日快乐')
  await expect(page.locator('.recipient-basics')).toContainText('公开邀请')
  expect((await state(page)).cases.teacher.curator).toBe(false)
})

test('照片模式不带旧文字，写回忆保留草稿，表情可独立提交', async ({ page }) => {
  await page.goto('/')
  await chapter(page, '留下我的回忆').click()
  await page.getByRole('textbox', { name: '共创内容', exact: true }).fill('这段回忆先保留。')
  await expect(page.locator('.editor-paper .ai-polish-panel')).toBeVisible()
  await page.getByRole('button', { name: '放照片', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '共创内容', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '选择要送出的照片', exact: false }).click()
  await page.getByRole('button', { name: '路过的风景 · 校园树荫', exact: false }).click()
  expect((await state(page)).cases.teacher.body).toBe('')
  await page.getByRole('button', { name: '写回忆', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '共创内容', exact: true })).toHaveValue(
    '这段回忆先保留。',
  )
  await page.getByRole('button', { name: '送祝福', exact: true }).click()
  await page.getByRole('button', { name: '选择谢谢表情', exact: true }).click()
  await page.getByRole('button', { name: '预览这份心意', exact: true }).click()
  await expect(page.locator('.selected-sticker')).toBeVisible()
  await page.getByRole('checkbox', { name: '送给陈老师，用于这次荣休礼' }).check()
  await page.getByRole('checkbox', { name: '同意在本次荣休仪式上展示' }).check()
  await page.getByRole('button', { name: '确认提交', exact: true }).click()
  expect((await state(page)).cases.teacher.submitted).toBe(true)
})

test('语音随仪式和礼后祝福在相框可播放', async ({ page }) => {
  await page.goto('/')
  await chapter(page, '留下我的回忆').click()
  await page.getByRole('button', { name: '用声音', exact: true }).click()
  await page.getByRole('button', { name: '开始语音演示', exact: true }).click()
  await page.getByRole('button', { name: '结束语音演示', exact: true }).click()
  await page.getByRole('button', { name: '预览这份心意', exact: true }).click()
  await page.getByRole('checkbox', { name: '送给陈老师，用于这次荣休礼' }).check()
  await page.getByRole('checkbox', { name: '同意在本次荣休仪式上展示' }).check()
  await page.getByRole('button', { name: '确认提交', exact: true }).click()
  await page.getByRole('button', { name: '查看自动整理的礼物', exact: false }).click()
  await page.getByRole('button', { name: '仪式：一段回忆', exact: true }).click()
  const sound = page.locator('.frame-screen audio')
  await expect(sound).toBeVisible()
  await expect.poll(() => sound.evaluate((el: HTMLAudioElement) => el.duration)).toBeGreaterThan(1)
  await sound.evaluate((el: HTMLAudioElement) => el.play())
  await expect
    .poll(() => sound.evaluate((el: HTMLAudioElement) => el.currentTime))
    .toBeGreaterThan(0)
  await page.screenshot({ path: '../../output/rongxiu-v2-voice.png', fullPage: true })
  await chapter(page, '再送一份心意').click()
  await page.getByRole('button', { name: '再添一段声音（示例）', exact: false }).click()
  await page.getByRole('button', { name: '选择岁岁平安表情', exact: true }).click()
  await page.getByRole('button', { name: '送给陈老师', exact: true }).click()
  await page.getByRole('button', { name: '看看相框收到', exact: false }).click()
  await expect(page.locator('.received-letter audio')).toBeVisible()
  await expect(page.locator('.received-letter .selected-sticker')).toBeVisible()
})
