import type { PrototypeScenario } from '../scenarioTypes'
import type { GalleryPhoto } from '../../types'

const amaPhoto = (fileName: string) => `/scenario/ama-letter/photos/${fileName}`
const amaAvatar = (fileName: string) => `/scenario/ama-letter/avatars/${fileName}`
const amaInteraction = (fileName: string) => `/scenario/ama-letter/interactions/${fileName}`
const amaMemoir = (fileName: string) => `/scenario/ama-letter/memoir/${fileName}`

const amaPersonalAlbumPhotos: GalleryPhoto[] = [
  {
    id: 'gallery-101',
    url: amaPhoto('watermark-free/old-street-night.png'),
    alt: '夜晚骑楼老街亮着戏院和店铺灯牌',
    title: '夜里亮起来的老街',
    uploadedAt: '2026-06-24T18:36:00+08:00',
    uploadedById: 'member-elder-ye',
    uploadedByName: '叶淑柔',
    isCached: true,
    voiceNoteDurationSeconds: 22,
    voiceNoteText: '这张是我年轻时常走的骑楼老街，大概是晚上戏院快开场的时候。那时我会站在灯牌底下等人，听黄包车铃声、看卖糖葱薄饼的小摊。日子不宽，可街灯一亮，心里就觉得还有热闹可盼。',
    aiTitle: '灯牌下的老街夜色',
    aiCategories: ['普通相册', '城市/汕头', '事件/老街与民俗', '怀旧/老街旧影', '物件/老街物件'],
    metadataSummary: '夜晚骑楼、戏院灯牌和街口人影，适合归入老街记忆与城市生活。',
  },
  {
    id: 'gallery-102',
    url: amaPhoto('watermark-free/yingge-street.png'),
    alt: '年轻时的叶淑柔走在老街榕树下的英歌队伍前',
    title: '年轻时走英歌',
    uploadedAt: '2026-06-23T16:30:00+08:00',
    uploadedById: 'member-elder-ye',
    uploadedByName: '叶淑柔',
    isCached: true,
    voiceNoteDurationSeconds: 24,
    voiceNoteText: '这张是我年轻时在老街榕树下走英歌。正月里锣鼓一响，我走在队伍前头，心里其实有点紧张，但人一站直，步子就有了精神。那时候年轻，最怕走不好，也最舍不得错过这份热闹。',
    aiTitle: '年轻时走在锣鼓声里',
    aiCategories: ['普通相册', '人物/叶淑柔', '城市/汕头', '事件/青春相伴', '事件/老街与民俗', '节日/正月', '怀旧/年轻时的淑柔', '合照/多人合照', '合照/包含我'],
    metadataSummary: '年轻叶淑柔出现在英歌队伍前，适合归入人物、节日民俗和年轻时候。',
  },
  {
    id: 'gallery-103',
    url: amaPhoto('watermark-free/rickshaw-old-street.png'),
    alt: '白天老街上人力车和路边店铺',
    title: '黄包车走过街口',
    uploadedAt: '2026-06-22T15:20:00+08:00',
    uploadedById: 'member-elder-ye',
    uploadedByName: '叶淑柔',
    isCached: true,
    voiceNoteDurationSeconds: 21,
    voiceNoteText: '这是我记忆里白天的骑楼街。街上有黄包车、茶楼和布店，我年轻时常去那边办事，买完东西还会多站一会儿，听听谁家来了信、谁家孩子回来了。',
    aiTitle: '白天的骑楼街口',
    aiCategories: ['普通相册', '城市/汕头', '事件/老街与民俗', '怀旧/老街旧影', '物件/旧交通'],
    metadataSummary: '白天骑楼老街和黄包车，适合归入老街地点、旧交通与城市记忆。',
  },
  {
    id: 'gallery-104',
    url: amaPhoto('watermark-free/family-tea-table.png'),
    alt: '年轻时的谢南枝和家人围坐在木桌边喝工夫茶',
    title: '南枝在茶桌边',
    uploadedAt: '2026-06-21T09:20:00+08:00',
    uploadedById: 'member-elder-ye',
    uploadedByName: '叶淑柔',
    isCached: true,
    voiceNoteDurationSeconds: 25,
    voiceNoteText: '这张是在老宅茶桌边拍的，里面笑得很甜的女孩子是南枝年轻时候。那天大家围着喝工夫茶，她一边听大人讲话，一边偷偷看镜头。我们姐妹那时就是这样，茶泡开了，话也慢慢说开。',
    aiTitle: '南枝年轻时候的茶桌照',
    aiCategories: ['普通相册', '人物/谢南枝', '人物/全家', '城市/汕头', '事件/茶桌与团圆', '合照/多人合照', '合照/家庭合照', '物件/茶具与茶叶'],
    metadataSummary: '年轻谢南枝出现在茶桌合影里，适合归入谢南枝、家庭合影和工夫茶场景。',
  },
  {
    id: 'gallery-105',
    url: amaPhoto('watermark-free/qiaopi-bank-front.png'),
    alt: '写着裕丰银信的旧楼门面和侨批相关招牌',
    title: '侨批寄来的地方',
    uploadedAt: '2026-06-20T11:12:00+08:00',
    uploadedById: 'member-elder-ye',
    uploadedByName: '叶淑柔',
    isCached: true,
    voiceNoteDurationSeconds: 24,
    voiceNoteText: '这张是侨批局门口，让我想起年轻时去问木生来信的日子。那时一封信、一点汇款，都要经过这样的地方才到手。我站在门口装得很平静，其实手心一直攥着。',
    aiTitle: '等一封侨批到家',
    aiCategories: ['普通相册', '城市/汕头', '事件/侨批与旧信', '物件/侨批信件', '怀旧/侨批旧址'],
    metadataSummary: '旧银信机构门面与侨批招牌，适合归入侨批、旧信和等待木生的故事线。',
  },
  {
    id: 'gallery-106',
    url: amaPhoto('watermark-free/office-ledger.png'),
    alt: '郑木生在泰国旧办公室里伏案登记和办事',
    title: '木生在泰国办事',
    uploadedAt: '2026-06-19T10:08:00+08:00',
    uploadedById: 'member-elder-ye',
    uploadedByName: '叶淑柔',
    isCached: true,
    voiceNoteDurationSeconds: 20,
    voiceNoteText: '这张是南枝寄来给我看的，说像木生当年在泰国那边办事的地方。桌上摊着登记簿，人人都低头写字。南枝说木生那时常跑这些地方，办工、汇钱、问船期，忙完还惦记着给家里写信。',
    aiTitle: '木生在南洋办事的日子',
    aiCategories: ['普通相册', '人物/郑木生', '人物/谢南枝', '城市/曼谷', '事件/木生在南洋', '怀旧/南洋旧场景', '物件/票据账簿'],
    metadataSummary: '南枝寄来的泰国旧办公室场景，关联木生在南洋办事、汇钱和写信的日子。',
  },
  {
    id: 'gallery-107',
    url: amaPhoto('watermark-free/field-tree-rest.png'),
    alt: '年轻时的叶淑柔和郑木生在黄昏田边树下约会',
    title: '田边树下的约会',
    uploadedAt: '2026-06-18T15:08:00+08:00',
    uploadedById: 'member-elder-ye',
    uploadedByName: '叶淑柔',
    isCached: true,
    voiceNoteDurationSeconds: 23,
    voiceNoteText: '这张是我和木生年轻时在田边树下见面的样子。那时快天黑了，风里有稻草味，我们坐得不远，话也不敢说太多。可就那么一会儿，我到现在还记得，他低头笑的时候很安静。',
    aiTitle: '黄昏树下的年轻心事',
    aiCategories: ['普通相册', '人物/叶淑柔', '人物/郑木生', '城市/汕头', '事件/青春相伴', '合照/两人合照', '合照/包含我', '怀旧/年轻时的我们'],
    metadataSummary: '年轻的淑柔和木生在田边树下见面，适合归入两人合照、青春相伴和年轻时的我们。',
  },
  {
    id: 'gallery-108',
    url: amaPhoto('watermark-free/rickshaw-sunset.png'),
    alt: '泰国夕阳下的老街口停着一辆黄包车',
    title: '木生走过的泰国街口',
    uploadedAt: '2026-06-17T17:22:00+08:00',
    uploadedById: 'member-elder-ye',
    uploadedByName: '叶淑柔',
    isCached: true,
    voiceNoteDurationSeconds: 20,
    voiceNoteText: '这张也是南枝寄来的，说这是木生当年在泰国常走过的街口。夕阳落下去，黄包车停在那里，街上慢慢安静下来。南枝说他下工后常从这样的路走回去，心里还惦记着潮汕家里。',
    aiTitle: '木生走过的南洋街口',
    aiCategories: ['普通相册', '人物/郑木生', '人物/谢南枝', '城市/曼谷', '事件/木生在南洋', '怀旧/南洋旧场景', '物件/旧交通'],
    metadataSummary: '南枝寄来的泰国街口场景，关联木生在南洋下工后的路和对潮汕家的牵挂。',
  },
  {
    id: 'gallery-109',
    url: amaPhoto('album-109-flag-procession.png'),
    alt: '1945年的潮汕老街上，年轻姑娘随扛标旗队伍穿过围观人群',
    title: '1945年的扛标旗队伍',
    uploadedAt: '2026-07-17T16:20:00+08:00',
    uploadedById: 'member-elder-ye',
    uploadedByName: '叶淑柔',
    isCached: true,
    voiceNoteDurationSeconds: 22,
    voiceNoteText: '这张老照片让我想起年轻时参加扛标旗的日子。街坊都围在路边看，锣鼓一响，人也跟着精神起来。木生就是在那样热闹的人群里第一次看见我的。',
    aiTitle: '木生第一次看见我的那天',
    aiCategories: ['普通相册', '人物/叶淑柔', '人物/郑木生', '城市/汕头', '时间/1945年', '事件/扛标旗', '事件/老街与民俗', '怀旧/历史影像', '合照/多人合照'],
    metadataSummary: '1945年扛标旗队伍穿过老街的历史画面，关联淑柔与木生的初见。',
  },
  {
    id: 'gallery-110',
    url: amaPhoto('album-110-siam-old-street.png'),
    alt: '1952年的暹罗唐人街旧景，街口有人力车和临街商铺',
    title: '1952年的暹罗旧街',
    uploadedAt: '2026-07-17T16:18:00+08:00',
    uploadedById: 'member-nanzhi',
    uploadedByName: '谢南枝',
    isCached: true,
    voiceNoteDurationSeconds: 20,
    voiceNoteText: '这是南枝帮我找来的旧街照片。木生年轻时在暹罗谋生，走过的街大概就是这个样子。看到人力车和老招牌，我就会想起他在信里说的一切都好。',
    aiTitle: '木生走过的暹罗旧街',
    aiCategories: ['普通相册', '人物/郑木生', '人物/谢南枝', '城市/曼谷', '时间/1952年', '事件/木生在南洋', '怀旧/南洋旧场景', '物件/旧交通'],
    metadataSummary: '1952年暹罗唐人街旧景，关联木生在南洋奔走谋生的日子。',
  },
  {
    id: 'gallery-111',
    url: amaPhoto('album-111-pocket-watch-restoration.jpg'),
    alt: '郑木生旧怀表的斑驳实拍与AI复原效果并排对照',
    title: '旧怀表的实拍与复原',
    uploadedAt: '2026-07-17T16:16:00+08:00',
    uploadedById: 'member-elder-ye',
    uploadedByName: '叶淑柔',
    isCached: true,
    voiceNoteDurationSeconds: 18,
    voiceNoteText: '这只怀表旧得已经看不清了，拾光叙帮我复原以后，才又看见它年轻时的样子。一个旧物件放了这么多年，留下来的不只是样子，还有木生的那份心意。',
    aiTitle: '滴答声里的旧时光',
    aiCategories: ['普通相册', '人物/郑木生', '时间/旧时', '物件/旧怀表', '事件/旧物与念想', '怀旧/旧物焕新', 'AI生成'],
    metadataSummary: '同一只旧怀表的斑驳实拍与AI复原效果，适合作为旧物焕新的前后对照。',
  },
]

const amaInteractionPhotos: GalleryPhoto[] = [
  {
    id: 'interaction-gallery-001',
    url: amaInteraction('interaction-01.png'),
    alt: '叶淑柔坐在老宅院子里使用智能相框发动态',
    title: '阿嫲学会发动态',
    uploadedAt: '2026-06-29T09:15:00+08:00',
    uploadedById: 'member-elder-ye',
    uploadedByName: '叶淑柔',
    isCached: true,
    voiceNoteDurationSeconds: 21,
    voiceNoteText: '看看晓伟给我买的这个机器，挺沉一个，还挺聪明，随便说几句话，它就帮我变成小文章做出来了，还挺好玩，你们看看我这个动态发出来了吗？',
    aiTitle: '老宅院子里的第一条动态',
    aiCategories: ['家庭互动', '人物/叶淑柔', '城市/汕头', '物件/智能相框', '事件/相框里的新鲜事'],
    metadataSummary: '叶淑柔坐在老宅院子里用相框发动态，适合归入阿嫲本人、老宅和智能相框使用场景。',
  },
  {
    id: 'interaction-gallery-002',
    url: amaInteraction('interaction-02.png'),
    alt: '叶淑柔在厨房里点评一盘无米粿',
    title: '阿嫲点评无米粿',
    uploadedAt: '2026-06-29T13:30:00+08:00',
    uploadedById: 'member-elder-ye',
    uploadedByName: '叶淑柔',
    isCached: true,
    voiceNoteDurationSeconds: 25,
    voiceNoteText: '刚才老大在厨房里捣鼓半天，说是给我做的无米粿，看这绿的，要别人做的我还不敢吃呢😝韭菜现在特别嫩，孩子们也多吃👍',
    aiTitle: '韭菜嫩，心意也热',
    aiCategories: ['家庭互动', '人物/叶淑柔', '食物/无米粿', '城市/汕头', '人物/郑楚卿', '事件/厨房与老味道'],
    metadataSummary: '叶淑柔在厨房里尝无米粿，画面主体是阿嫲本人，也关联楚卿做菜给母亲吃。',
  },
  {
    id: 'interaction-gallery-003',
    url: amaInteraction('interaction-03.png'),
    alt: '叶淑柔夜晚坐在相框前看郑木生旧信和年轻影像',
    title: '相框响起木生的声音',
    uploadedAt: '2026-06-28T20:00:00+08:00',
    uploadedById: 'member-xiaowei',
    uploadedByName: '郑晓伟',
    isCached: true,
    voiceNoteDurationSeconds: 28,
    voiceNoteText: '相框突然给我弹出来一封木生的信，看的我这心里难受，相片里还那么年轻，看我现在这老样子，他现在要还在也老了吧。木生啊，六十多年了，家里的孩子们都出息了，都挺好的。你在那边，安心吧。',
    aiTitle: '江海万里，心中念你',
    aiCategories: ['时间胶囊', '人物/叶淑柔', '人物/郑木生', '城市/汕头', '物件/侨批信件', '物件/智能相框', '事件/侨批与旧信'],
    metadataSummary: '叶淑柔在夜里看相框播放木生旧信，画面同时关联淑柔、木生和侨批记忆。',
  },
  {
    id: 'interaction-gallery-004',
    url: amaInteraction('interaction-04.png'),
    alt: '叶淑柔在院子里整理和晾晒郑木生当年的旧信',
    title: '院子里晒旧信',
    uploadedAt: '2026-06-29T14:30:00+08:00',
    uploadedById: 'member-elder-ye',
    uploadedByName: '叶淑柔',
    isCached: true,
    voiceNoteDurationSeconds: 24,
    voiceNoteText: '今天下午没下雨，我在院子里把木生当年的那些信拿出来晒了晒。以前不知道，现在摸着这些纸，满脑子都是南枝在邮局排队汇款的样子。',
    aiTitle: '摸着旧信想起南枝',
    aiCategories: ['家庭互动', '人物/叶淑柔', '人物/郑木生', '物件/侨批信件', '城市/汕头', '人物/谢南枝', '事件/侨批与旧信'],
    metadataSummary: '叶淑柔在院子里整理和晾晒旧信，画面主体是阿嫲本人，也关联木生侨批和南枝当年的照应。',
  },
  {
    id: 'interaction-gallery-005',
    url: amaInteraction('interaction-05.png'),
    alt: '郑晓伟在室内攀岩墙上运动',
    title: '晓伟周末攀岩',
    uploadedAt: '2026-06-27T09:30:00+08:00',
    uploadedById: 'member-xiaowei',
    uploadedByName: '郑晓伟',
    isCached: true,
    voiceNoteDurationSeconds: 17,
    voiceNoteText: '周末早起去室内攀岩出出汗！阿嫲，看你孙子多精神！下次回去教你玩！',
    aiTitle: '孙子发来的精神劲',
    aiCategories: ['家庭互动', '人物/郑晓伟', '城市/深圳', '事件/晚辈近况', '运动/攀岩'],
    metadataSummary: '晓伟把周末运动发给阿嫲看，引来家人的关心和打趣。',
  },
  {
    id: 'interaction-gallery-006',
    url: amaInteraction('interaction-06.png'),
    alt: '郑晓伟复刻潮汕蚝烙失败的厨房画面',
    title: '蚝烙复刻翻车',
    uploadedAt: '2026-06-27T12:40:00+08:00',
    uploadedById: 'member-xiaowei',
    uploadedByName: '郑晓伟',
    isCached: true,
    voiceNoteDurationSeconds: 22,
    voiceNoteText: '紧急求助！！我刚才心血来潮，用“拾光叙”提取了阿嬷回忆录里“潮汕蚝烙”的菜谱，自己在家复刻。为什么我煎出来的东西，有点不太对啊？？？阿嬷，您的AI菜谱是不是少写了一步“先放油”啊！',
    aiTitle: 'AI菜谱也救不了火候',
    aiCategories: ['家庭互动', '人物/郑晓伟', '食物/蚝烙', '城市/深圳', '事件/厨房与老味道'],
    metadataSummary: '晓伟照着阿嫲回忆录里的菜谱复刻蚝烙，最后向全家求助。',
  },
  {
    id: 'interaction-gallery-007',
    url: amaInteraction('interaction-07.png'),
    alt: '一锅水放多了的绿色无米粿面糊',
    title: '无米粿又翻车了',
    uploadedAt: '2026-06-29T12:15:00+08:00',
    uploadedById: 'member-chuqing',
    uploadedByName: '郑楚卿',
    isCached: true,
    voiceNoteDurationSeconds: 19,
    voiceNoteText: '救命啊家人们！今天本来想给妈露一手做地道的无米粿，结果水放多了，现在锅里变成了一坨绿色的史莱姆……[捂脸][流泪] 谁能假装没看见？千万别让阿嬷看到这条！',
    aiTitle: '女儿厨房里的热闹',
    aiCategories: ['家庭互动', '食物/无米粿', '人物/郑楚卿', '城市/汕头', '事件/厨房与老味道'],
    metadataSummary: '郑楚卿想给阿嫲露一手，结果把无米粿做成了绿色面糊。',
  },
  {
    id: 'interaction-gallery-008',
    url: amaInteraction('interaction-08.png'),
    alt: '叶淑柔在老街市场挑鸡和买菜',
    title: '谁照顾谁呀',
    uploadedAt: '2026-07-03T10:15:00+08:00',
    uploadedById: 'member-chuqing',
    uploadedByName: '郑楚卿',
    isCached: true,
    voiceNoteDurationSeconds: 20,
    voiceNoteText: '今天跟老妈去市场挑了靓鸡，还得她老人家出手，选的就是肥啊👍，等大家过年回来我再给你们炖~',
    aiTitle: '老街市场里的挑鸡课',
    aiCategories: ['家庭互动', '人物/叶淑柔', '城市/汕头', '食物/鸡汤', '人物/郑楚卿', '事件/家人照护'],
    metadataSummary: '叶淑柔在市场里挑鸡买菜，画面主体是阿嫲本人，也关联楚卿陪母亲买菜。',
  },
  {
    id: 'interaction-gallery-009',
    url: amaInteraction('interaction-09.png'),
    alt: 'AI生成的年轻叶淑柔在老街民俗队伍里扛着标旗',
    title: '扛标旗那天',
    uploadedAt: '2026-07-01T17:20:00+08:00',
    uploadedById: 'member-chuqing',
    uploadedByName: '郑楚卿',
    isCached: true,
    voiceNoteDurationSeconds: 24,
    voiceNoteText: '用阿嬷的老照片生成了当年她扛标旗的盛况，也是在这里父亲对她一见钟情，开始了一生的相守',
    aiTitle: '木生一眼看见的标旗姑娘',
    aiCategories: ['家庭互动', '人物/叶淑柔', '人物/郑木生', '人物/郑楚卿', '城市/汕头', '事件/青春相伴', '事件/老街与民俗', '怀旧/年轻时的淑柔', 'AI生成'],
    metadataSummary: '楚卿用阿嫲老照片生成年轻时扛标旗的场景，也把木生与淑柔一见钟情的故事重新带出来。',
  },
  {
    id: 'interaction-gallery-010',
    url: amaInteraction('interaction-10.png'),
    alt: '郑楚龙清理老宅院子并买好凤凰单丛茶',
    title: '楚龙回老宅',
    uploadedAt: '2026-06-29T15:40:00+08:00',
    uploadedById: 'member-chulong',
    uploadedByName: '郑楚龙',
    isCached: true,
    voiceNoteDurationSeconds: 21,
    voiceNoteText: '今天回老宅把院子里的青苔清理了一下，免得妈走路滑倒。顺便去老街的茶铺买了妈最爱喝的凤凰单丛，喝茶喽',
    aiTitle: '清青苔，也带单丛茶',
    aiCategories: ['家庭互动', '人物/郑楚龙', '城市/汕头', '物件/茶具与茶叶', '事件/家人照护'],
    metadataSummary: '郑楚龙回老宅清院子，也带来凤凰单丛茶，适合归入楚龙、老宅和茶叶线索。',
  },
  {
    id: 'interaction-gallery-011',
    url: amaInteraction('interaction-11.png'),
    alt: '郑木生当年留下的旧怀表与AI复原后的金色怀表对比',
    title: '旧怀表又响了一下',
    uploadedAt: '2026-07-02T10:10:00+08:00',
    uploadedById: 'member-chulong',
    uploadedByName: '郑楚龙',
    isCached: true,
    voiceNoteDurationSeconds: 22,
    voiceNoteText: '兄弟姐妹们看到找到什么宝贝了，这是阿公当年留下的那个旧怀表！表针早就不转了，但我用拾光叙的【AI旧物焕新】扫了一下，看看复原后多漂亮，还给配了一段滴答滴答的音效。给老妈听的都有点难受了。',
    aiTitle: '滴答声里的定情信物',
    aiCategories: ['家庭互动', '物件/旧怀表', '人物/郑木生', '城市/汕头', '怀旧/旧物焕新', '人物/郑楚龙', '事件/旧物与念想'],
    metadataSummary: '旧怀表是木生留下的物件，由楚龙在老宅翻出，适合归入木生、旧物和怀表记忆。',
  },
  {
    id: 'interaction-gallery-012',
    url: amaInteraction('interaction-12.png'),
    alt: '曼谷街边盛开的木棉花',
    title: '曼谷的木棉花',
    uploadedAt: '2026-06-28T18:00:00+08:00',
    uploadedById: 'member-nanzhi',
    uploadedByName: '谢南枝',
    isCached: true,
    voiceNoteDurationSeconds: 20,
    voiceNoteText: '看看湄南河边的木棉花今天开了，落了一地红。突然想起老家南山的木棉，应该也是这时候开吧？ 家人们多发点美照啊',
    aiTitle: '远方妹妹的问候',
    aiCategories: ['家庭互动', '人物/谢南枝', '城市/曼谷', '植物/木棉花', '事件/远方亲人问候'],
    metadataSummary: '谢南枝从曼谷发来木棉花，画面是远方地点和花，也代表南枝对淑柔的问候。',
  },
  {
    id: 'interaction-gallery-013',
    url: amaInteraction('interaction-13.png'),
    alt: '郑楚远深夜加班时在窗边吃白粥和潮汕家常菜，桌上相框亮着家人的动态',
    title: '加班夜里的乡味',
    uploadedAt: '2026-07-02T21:30:00+08:00',
    uploadedById: 'member-chuyuan',
    uploadedByName: '郑楚远',
    isCached: true,
    voiceNoteDurationSeconds: 21,
    voiceNoteText: '老妈不用担心我，忙碌的日子也有好好吃饭✌忽然就想咱家里那一口白粥和无米粿啦。等下个月项目结束，一定带素琴和晓伟回老家看您。',
    aiTitle: '最想念还是妈做的白粥',
    aiCategories: ['家庭互动', '人物/郑楚远', '食物/白粥', '食物/无米粿', '城市/深圳', '事件/晚辈近况'],
    metadataSummary: '楚远加班夜里吃饭，想起母亲做的白粥和无米粿，适合归入楚远和老味道。',
  },
  {
    id: 'interaction-gallery-016',
    url: amaInteraction('interaction-16.png'),
    alt: '暹罗旧街上一个男人骑着三轮车穿过唐人街',
    title: '暹罗唐人街旧事',
    uploadedAt: '2026-07-02T18:00:00+08:00',
    uploadedById: 'member-chulong',
    uploadedByName: '郑楚龙',
    isCached: true,
    voiceNoteDurationSeconds: 18,
    voiceNoteText: '当年父亲就是在这里靠自己的双腿，一车车为千里之外的我们撑起了生活。',
    aiTitle: '父亲在暹罗撑起的生活',
    aiCategories: ['家庭互动', '人物/郑楚龙', '人物/郑木生', '城市/曼谷', '事件/木生在南洋', '怀旧/南洋旧场景', '物件/旧交通'],
    metadataSummary: '楚龙发来暹罗唐人街旧景，借父亲当年一车车奔走谋生的画面，把木生在南洋撑家的故事讲给晚辈。',
  },
  {
    id: 'interaction-gallery-014',
    url: amaInteraction('interaction-14.png'),
    alt: '林素琴给叶淑柔买的白色和浅色香云纱夏装',
    title: '素琴寄来的香云纱',
    uploadedAt: '2026-06-28T14:15:00+08:00',
    uploadedById: 'member-lin-suqin',
    uploadedByName: '林素琴',
    isCached: true,
    voiceNoteDurationSeconds: 19,
    voiceNoteText: '今天逛商场看到几件白色和浅色的香云纱夏装，摸着特别舒服，立刻就给老妈下单了，期待咱妈穿上新衣服美美拍照呀',
    aiTitle: '白色衣服衬人',
    aiCategories: ['家庭互动', '衣物/香云纱', '人物/林素琴', '人物/叶淑柔', '城市/深圳', '事件/家人照护'],
    metadataSummary: '画面是素琴给叶淑柔挑的浅色香云纱夏装，适合归入衣物、素琴和阿嫲穿着照护。',
  },
  {
    id: 'interaction-gallery-015',
    url: amaInteraction('interaction-15.png'),
    alt: '谢南枝在曼谷唐人街挑药油和干货',
    title: '曼谷唐人街的药油',
    uploadedAt: '2026-06-29T10:20:00+08:00',
    uploadedById: 'member-xie-zehua',
    uploadedByName: '谢泽华',
    isCached: true,
    voiceNoteDurationSeconds: 20,
    voiceNoteText: '今天陪我妈（南枝）逛曼谷的唐人街。老太太走到哪都要看看有没有好点的药油和干货，说要给潮汕的淑柔伯母寄过去，走到哪都惦记着咱们这个家',
    aiTitle: '远方亲人也连上线了',
    aiCategories: ['家庭互动', '人物/谢南枝', '城市/曼谷', '物件/药油干货', '人物/谢泽华', '事件/远方亲人问候'],
    metadataSummary: '谢南枝在曼谷唐人街挑药油和干货，泽华负责拍照上传，适合归入南枝和远方亲人。',
  },
  {
    id: 'interaction-gallery-017',
    url: amaInteraction('interaction-17.png'),
    alt: '郑晓伟一家三口在明亮的厨房里教孩子包饺子',
    title: '孩子第一次学包饺子',
    uploadedAt: '2026-07-17T11:10:00+08:00',
    uploadedById: 'member-xiaowei',
    uploadedByName: '郑晓伟',
    isCached: true,
    voiceNoteText: '今天家里包饺子，小宝看见也非要上手。果不其然都煮破了，一家人喝了碗肉菜粥哈哈~',
    aiTitle: '小宝第一次包饺子',
    aiCategories: ['家庭互动', '人物/郑晓伟', '人物/孩子', '城市/深圳', '时间/2026年', '食物/饺子', '事件/烟火日常', '事件/亲子时光', '合照/家庭合照'],
    metadataSummary: '晓伟一家在厨房教孩子包饺子，记录晚辈自己的家庭生活。',
  },
  {
    id: 'interaction-gallery-018',
    url: amaInteraction('interaction-18.png'),
    alt: '谢南枝和泽华在曼谷庭院里一起翻看老照片，桌边开着荷花',
    title: '曼谷庭院里的牵挂',
    uploadedAt: '2026-07-17T10:26:00+08:00',
    uploadedById: 'member-nanzhi',
    uploadedByName: '谢南枝',
    isCached: true,
    voiceNoteText: '今天曼谷的阳光特别好，院子里的荷花全开啦。下午泽华回来看我，聊着聊着就想家了。嫂子，老家现在冷不冷？你这几天腿还疼吗？🌸🥭',
    aiTitle: '曼谷阳光下想起老家',
    aiCategories: ['家庭互动', '人物/谢南枝', '人物/谢泽华', '城市/曼谷', '时间/2026年', '事件/远方亲人问候', '事件/烟火日常', '合照/两人合照'],
    metadataSummary: '南枝在曼谷庭院和泽华翻看照片，也隔着相框询问淑柔的近况。',
  },
  {
    id: 'interaction-gallery-019',
    url: amaInteraction('interaction-19.png'),
    alt: '郑晓伟一家三口牵着孩子在海边捡贝壳',
    title: '周末带家人去看海',
    uploadedAt: '2025-07-13T16:40:00+08:00',
    uploadedById: 'member-xiaowei',
    uploadedByName: '郑晓伟',
    isCached: true,
    voiceNoteText: '今天带孩子去看海。他捡了满满一桶小贝壳，说要带给太奶奶。',
    aiTitle: '晓伟发来｜周末带家人去看海',
    aiCategories: ['家庭互动', '人物/郑晓伟', '人物/孩子', '城市/汕头', '地点/海边', '时间/2025年', '事件/带孩子', '事件/出游', '合照/家庭合照'],
    metadataSummary: '晓伟去年带孩子去海边，孩子捡了一桶贝壳想送给太奶奶。',
  },
]

const amaGalleryPhotos: GalleryPhoto[] = [...amaPersonalAlbumPhotos, ...amaInteractionPhotos]

const getAmaPhotoById = (id: string) => {
  const photo = amaGalleryPhotos.find((item) => item.id === id)
  if (!photo) return amaGalleryPhotos[0]
  return photo
}

const amaWishlistItems = [
  {
    id: 'ama-wish-elder-nanzhi-call',
    ownerId: 'member-elder-ye',
    ownerName: '叶淑柔',
    ownerType: 'elder' as const,
    title: '每周和南枝说一次话',
    summary: '不一定聊大事，听见彼此声音就安心。',
    reason: '阿嫲最惦记远在曼谷的妹妹，想把这些年没来得及说的话慢慢补回来。',
    category: '姐妹牵挂',
    status: 'scheduled' as const,
    statusLabel: '已约好',
    visibility: 'family' as const,
    participantNames: ['叶淑柔', '谢南枝'],
    nextStep: '晓伟周日晚饭后帮阿嫲拨给南枝',
    dateLabel: '每周日',
    photoUrl: getAmaPhotoById('interaction-gallery-012').url,
  },
  {
    id: 'ama-wish-elder-old-letters',
    ownerId: 'member-elder-ye',
    ownerName: '叶淑柔',
    ownerType: 'elder' as const,
    title: '把木生的旧信再读一遍',
    summary: '一封一封听完，把想回的话也录下来。',
    reason: '相框能把侨批读出来，阿嫲想趁精神好的时候，把那些旧信重新整理成给孩子听得懂的故事。',
    category: '旧信整理',
    status: 'responded' as const,
    statusLabel: '家人已回应',
    visibility: 'private' as const,
    participantNames: ['叶淑柔', '郑晓伟'],
    nextStep: '晓伟先扫描铁皮盒里的前三封信',
    dateLabel: '这周',
    photoUrl: getAmaPhotoById('interaction-gallery-003').url,
  },
  {
    id: 'ama-wish-elder-tea-table',
    ownerId: 'member-elder-ye',
    ownerName: '叶淑柔',
    ownerType: 'elder' as const,
    title: '教孩子们冲一次工夫茶',
    summary: '茶杯要热，水要准，话也要慢慢说。',
    reason: '阿嫲觉得工夫茶不是喝茶那么简单，是家里人坐下来、把心放慢的规矩。',
    category: '家传手艺',
    status: 'wish' as const,
    statusLabel: '想做',
    visibility: 'family' as const,
    participantNames: ['叶淑柔', '郑楚龙', '郑晓伟'],
    nextStep: '楚龙下次回来带凤凰单丛，晓伟负责录像',
    dateLabel: '下次回老宅',
    photoUrl: getAmaPhotoById('gallery-104').url,
  },
  {
    id: 'ama-wish-elder-wumiguo',
    ownerId: 'member-elder-ye',
    ownerName: '叶淑柔',
    ownerType: 'elder' as const,
    title: '再做一次无米粿',
    summary: '让楚卿在旁边学，晓伟负责别再笑场。',
    reason: '女儿和孙子都在复刻老味道，阿嫲想亲自把水量、火候和手感讲清楚。',
    category: '老味道',
    status: 'wish' as const,
    statusLabel: '想做',
    visibility: 'family' as const,
    participantNames: ['叶淑柔', '郑楚卿', '郑晓伟'],
    nextStep: '先让楚卿买韭菜和地瓜粉',
    dateLabel: '这个月',
    photoUrl: getAmaPhotoById('interaction-gallery-007').url,
  },
  {
    id: 'ama-wish-elder-new-coat',
    ownerId: 'member-elder-ye',
    ownerName: '叶淑柔',
    ownerType: 'elder' as const,
    title: '穿新外套拍一张照片',
    summary: '嘴上说贵，心里还是想给家人看看。',
    reason: '素琴和楚卿都说浅色衣服衬人，阿嫲想等天气好，在院子里拍一张现在的自己。',
    category: '现在的照片',
    status: 'completed' as const,
    statusLabel: '已完成',
    visibility: 'family' as const,
    participantNames: ['叶淑柔', '林素琴', '郑楚卿'],
    nextStep: '',
    dateLabel: '昨天',
    photoUrl: getAmaPhotoById('interaction-gallery-014').url,
  },
  {
    id: 'ama-wish-family-new-portrait',
    ownerId: 'family',
    ownerName: '全家',
    ownerType: 'family' as const,
    title: '拍一张新的老宅全家福',
    summary: '把远方的人也放进相框里，一起留在今年。',
    reason: '家里旧照片很多，但阿嫲也想留住现在的孩子们和自己。',
    category: '家庭合影',
    status: 'scheduled' as const,
    statusLabel: '已安排',
    participantNames: ['叶淑柔', '郑楚远', '林素琴', '郑楚龙', '郑楚卿', '郑晓伟'],
    nextStep: '楚远一家下次回来时，在老宅门口一起拍',
    dateLabel: '下月初',
    photoUrl: getAmaPhotoById('gallery-104').url,
  },
  {
    id: 'ama-wish-family-letters-book',
    ownerId: 'family',
    ownerName: '全家',
    ownerType: 'family' as const,
    title: '把侨批整理成一本小册子',
    summary: '旧信、照片和阿嫲的口述一起放进去。',
    reason: '这些信不只是木生和阿嫲的事，也是整个家的来处。',
    category: '家庭共创',
    status: 'responded' as const,
    statusLabel: '开始整理',
    participantNames: ['叶淑柔', '郑晓伟', '谢南枝'],
    nextStep: '先选三封最重要的信，配上阿嫲的语音',
    dateLabel: '慢慢整理',
    photoUrl: getAmaPhotoById('interaction-gallery-004').url,
  },
  {
    id: 'ama-wish-family-tea-dinner',
    ownerId: 'family',
    ownerName: '全家',
    ownerType: 'family' as const,
    title: '周末一起吃一顿潮汕家常饭',
    summary: '白粥、无米粿、蚝烙和一壶单丛茶。',
    reason: '楚远加班时最想念老家的味道，家里人想把这顿饭真正约起来。',
    category: '家庭约定',
    status: 'wish' as const,
    statusLabel: '想做',
    participantNames: ['叶淑柔', '郑楚远', '林素琴', '郑楚龙', '郑楚卿', '郑晓伟'],
    nextStep: '先在家庭群里定一个大家都能回来的周末',
    dateLabel: '这个月',
    photoUrl: getAmaPhotoById('gallery-104').url,
  },
  {
    id: 'ama-wish-family-nanzhi-visit',
    ownerId: 'family',
    ownerName: '全家',
    ownerType: 'family' as const,
    title: '帮阿嫲和南枝见上一面',
    summary: '先视频，再计划一次真正的重逢。',
    reason: '曼谷和汕头隔得远，但全家都想把这份姐妹牵挂往前推一步。',
    category: '远方团圆',
    status: 'wish' as const,
    statusLabel: '想做',
    participantNames: ['叶淑柔', '谢南枝', '谢泽华', '郑晓伟'],
    nextStep: '泽华先确认南枝的身体和出行安排',
    dateLabel: '今年内',
    photoUrl: getAmaPhotoById('interaction-gallery-015').url,
  },
  {
    id: 'ama-wish-family-clean-yard',
    ownerId: 'family',
    ownerName: '全家',
    ownerType: 'family' as const,
    title: '把老宅院子重新收拾好',
    summary: '青苔清掉，茶桌摆好，等家里人回来坐。',
    reason: '阿嫲每天都看着院子，楚龙想把她不方便做的活都接过去。',
    category: '老宅照看',
    status: 'completed' as const,
    statusLabel: '已完成',
    participantNames: ['叶淑柔', '郑楚龙'],
    nextStep: '',
    dateLabel: '今天',
    photoUrl: getAmaPhotoById('interaction-gallery-010').url,
  },
]

const response = (
  threadId: string,
  index: string,
  authorId: string,
  authorName: string,
  relation: string,
  method: 'voice' | 'text' | 'ai_generated',
  content: string,
  createdAt: string,
  durationSeconds?: number,
) => ({
  id: `${threadId}-${index}`,
  authorId,
  authorName,
  relation,
  method,
  content,
  createdAt,
  ...(durationSeconds ? { durationSeconds } : {}),
})

const amaInteractionThreads = [
  {
    id: 'thread-001',
    title: '阿嫲学会发动态',
    photoUrl: getAmaPhotoById('interaction-gallery-001').url,
    photoAlt: getAmaPhotoById('interaction-gallery-001').alt,
    photoLabel: '老宅院子',
    photoMeta: '6月29日 09:15',
    photoTone: 'moss' as const,
    senderId: 'member-elder-ye',
    senderName: '叶淑柔',
    initialContent: '看看晓伟给我买的这个机器，挺沉一个，还挺聪明，随便说几句话，它就帮我变成小文章做出来了，还挺好玩，你们看看我这个动态发出来了吗？',
    initialMethod: 'voice' as const,
    latestSnippet: '阿嬷真棒！这就学会发动态了',
    latestAt: '2026-06-29T10:08:00+08:00',
    unread: false,
    responses: [
      response('thread-001', 'a', 'member-elder-ye', '叶淑柔', '阿嬷', 'voice', '看看晓伟给我买的这个机器，挺沉一个，还挺聪明，随便说几句话，它就帮我变成小文章做出来了，还挺好玩，你们看看我这个动态发出来了吗？', '2026-06-29T09:15:00+08:00', 18),
      response('thread-001', 'b', 'member-chulong', '郑楚龙', '三叔', 'text', '妈，这么厉害呢👍👍👍', '2026-06-29T09:28:00+08:00'),
      response('thread-001', 'c', 'member-xiaowei', '郑晓伟', '孙子', 'text', '阿嬷真棒！这就学会发动态了！给阿嬷点赞！👍', '2026-06-29T10:08:00+08:00'),
    ],
  },
  {
    id: 'thread-002',
    title: '老大做的无米粿',
    photoUrl: getAmaPhotoById('interaction-gallery-002').url,
    photoAlt: getAmaPhotoById('interaction-gallery-002').alt,
    photoLabel: '厨房里的无米粿',
    photoMeta: '6月29日 13:30',
    photoTone: 'gold' as const,
    senderId: 'member-elder-ye',
    senderName: '叶淑柔',
    initialContent: '刚才老大在厨房里捣鼓半天，说是给我做的无米粿，看这绿的，要别人做的我还不敢吃呢😝韭菜现在特别嫩，孩子们也多吃👍',
    initialMethod: 'voice' as const,
    latestSnippet: '南枝啊，等腿脚利索了，嫂子飞去曼谷亲手给你做',
    latestAt: '2026-06-29T14:02:00+08:00',
    unread: false,
    responses: [
      response('thread-002', 'a', 'member-elder-ye', '叶淑柔', '阿嬷', 'voice', '刚才老大在厨房里捣鼓半天，说是给我做的无米粿，看这绿的，要别人做的我还不敢吃呢。韭菜现在特别嫩，孩子们也多吃。', '2026-06-29T13:30:00+08:00', 19),
      response('thread-002', 'b', 'member-chuqing', '郑楚卿', '大女儿', 'text', '呜呜呜，妈！我就知道你最心疼我！晓伟刚才还嘲笑我在“炼丹”！[大哭][抱抱]', '2026-06-29T13:42:00+08:00'),
      response('thread-002', 'c', 'member-nanzhi', '谢南枝', '妹妹', 'text', '嫂子好福气，儿媳妇这么孝顺。曼谷这边可吃不到这一口哦。', '2026-06-29T13:55:00+08:00'),
      response('thread-002', 'd', 'member-elder-ye', '叶淑柔', '阿嬷', 'voice', '南枝啊，等腿脚利索了，嫂子飞去曼谷亲手给你做！', '2026-06-29T14:02:00+08:00', 8),
    ],
  },
  {
    id: 'thread-003',
    title: '相框响起木生的声音',
    photoUrl: getAmaPhotoById('interaction-gallery-003').url,
    photoAlt: getAmaPhotoById('interaction-gallery-003').alt,
    photoLabel: '拾光时间胶囊',
    photoMeta: '6月28日 20:00',
    photoTone: 'paper' as const,
    senderId: 'member-elder-ye',
    senderName: '叶淑柔',
    initialContent: '相框突然给我弹出来一封木生的信，看的我这心里难受，相片里还那么年轻，看我现在这老样子，他现在要还在也老了吧。木生啊，六十多年了，家里的孩子们都出息了，都挺好的。你在那边，安心吧。',
    initialMethod: 'voice' as const,
    latestSnippet: '阿公一直都在陪着您，我们全家人也都陪着您',
    latestAt: '2026-06-28T20:26:00+08:00',
    unread: true,
    responses: [
      response('thread-003', 'a', 'member-elder-ye', '叶淑柔', '阿嬷', 'voice', '相框突然给我弹出来一封木生的信，看的我这心里难受，相片里还那么年轻，看我现在这老样子，他现在要还在也老了吧。木生啊，六十多年了，家里的孩子们都出息了，都挺好的。你在那边，安心吧。', '2026-06-28T20:00:00+08:00', 30),
      response('thread-003', 'b', 'member-xiaowei', '郑晓伟', '孙子', 'text', '阿嬷，阿公一直都在陪着您，我们全家人也都陪着您。❤️', '2026-06-28T20:12:00+08:00'),
      response('thread-003', 'c', 'member-nanzhi', '谢南枝', '妹妹', 'text', '嫂子，木生哥看到今天咱们一大家子这样，在天之灵一定会笑的。', '2026-06-28T20:18:00+08:00'),
      response('thread-003', 'd', 'member-chuqing', '郑楚卿', '女儿', 'text', '妈，明天咱们包饺子，全家一起在相框前给爸敬杯茶！', '2026-06-28T20:26:00+08:00'),
    ],
  },
  {
    id: 'thread-004',
    title: '院子里晒旧信',
    photoUrl: getAmaPhotoById('interaction-gallery-004').url,
    photoAlt: getAmaPhotoById('interaction-gallery-004').alt,
    photoLabel: '木生的旧信',
    photoMeta: '6月29日 14:30',
    photoTone: 'paper' as const,
    senderId: 'member-elder-ye',
    senderName: '叶淑柔',
    initialContent: '今天下午没下雨，我在院子里把木生当年的那些信拿出来晒了晒。以前不知道，现在摸着这些纸，满脑子都是南枝在邮局排队汇款的样子。',
    initialMethod: 'voice' as const,
    latestSnippet: '嫂子，晓伟有空多过来啊',
    latestAt: '2026-06-29T15:02:00+08:00',
    unread: false,
    responses: [
      response('thread-004', 'a', 'member-elder-ye', '叶淑柔', '阿嬷', 'voice', '今天下午没下雨，我在院子里把木生当年的那些信拿出来晒了晒。以前不知道，现在摸着这些纸，满脑子都是南枝在邮局排队汇款的样子。', '2026-06-29T14:30:00+08:00', 18),
      response('thread-004', 'b', 'member-nanzhi', '谢南枝', '妹妹', 'text', '嫂子，晓伟有空多过来啊，我带他吃好吃的。', '2026-06-29T14:46:00+08:00'),
      response('thread-004', 'c', 'member-chuqing', '郑楚卿', '大嫂（女儿）', 'text', '妈，您别在风口里坐太久，当心着凉，我这就过去收。', '2026-06-29T15:02:00+08:00'),
    ],
  },
  {
    id: 'thread-005',
    title: '晓伟周末攀岩',
    photoUrl: getAmaPhotoById('interaction-gallery-005').url,
    photoAlt: getAmaPhotoById('interaction-gallery-005').alt,
    photoLabel: '室内攀岩',
    photoMeta: '6月27日 09:30',
    photoTone: 'peach' as const,
    senderId: 'member-xiaowei',
    senderName: '郑晓伟',
    initialContent: '周末早起去室内攀岩出出汗！阿嫲，看你孙子多精神！下次回去教你玩！',
    initialMethod: 'text' as const,
    latestSnippet: '晓伟啊，爬那么高太危险了，快下来',
    latestAt: '2026-06-27T10:06:00+08:00',
    unread: false,
    responses: [
      response('thread-005', 'a', 'member-xiaowei', '郑晓伟', '孙子', 'text', '周末早起去室内攀岩出出汗！阿嫲，看你孙子多精神！下次回去教你玩！', '2026-06-27T09:30:00+08:00'),
      response('thread-005', 'b', 'member-lin-suqin', '林素琴', '晓伟妈妈', 'text', '郑晓伟你小心点！别摔着了，净让你阿嫲跟着操心。', '2026-06-27T09:48:00+08:00'),
      response('thread-005', 'c', 'member-elder-ye', '叶淑柔', '阿嫲', 'voice', '晓伟啊，爬那么高太危险了，快下来！满头大汗的，赶紧喝口温水。', '2026-06-27T09:55:00+08:00', 11),
      response('thread-005', 'd', 'member-chuyuan', '郑楚远', '爸爸', 'text', '小子体力不错，比你爸我当年强。', '2026-06-27T10:06:00+08:00'),
    ],
  },
  {
    id: 'thread-006',
    title: '蚝烙复刻翻车',
    photoUrl: getAmaPhotoById('interaction-gallery-006').url,
    photoAlt: getAmaPhotoById('interaction-gallery-006').alt,
    photoLabel: '厨房求助',
    photoMeta: '6月27日 12:40',
    photoTone: 'gold' as const,
    senderId: 'member-xiaowei',
    senderName: '郑晓伟',
    initialContent: '紧急求助！！我刚才心血来潮，用“拾光叙”提取了阿嬷回忆录里“潮汕蚝烙”的菜谱，自己在家复刻。为什么我煎出来的东西，有点不太对啊？？？阿嬷，您的AI菜谱是不是少写了一步“先放油”啊！',
    initialMethod: 'text' as const,
    latestSnippet: '周末回来，阿嫲亲手煎给你吃',
    latestAt: '2026-06-27T13:22:00+08:00',
    unread: false,
    responses: [
      response('thread-006', 'a', 'member-xiaowei', '郑晓伟', '孙子', 'text', '紧急求助！！我刚才心血来潮，用“拾光叙”提取了阿嬷回忆录里“潮汕蚝烙”的菜谱，自己在家复刻。为什么我煎出来的东西，有点不太对啊？？？阿嬷，您的AI菜谱是不是少写了一步“先放油”啊！', '2026-06-27T12:40:00+08:00'),
      response('thread-006', 'b', 'member-chuqing', '郑楚卿', '大嫂（女儿）', 'text', '郑晓伟你不要炸厨房！你阿嬷的厨艺是玄学，AI也学不会那种“火候适中”的！', '2026-06-27T12:51:00+08:00'),
      response('thread-006', 'c', 'member-chulong', '郑楚龙', '三叔', 'text', '晚上回来吃饭吧，你妈今天刚做了红桃粿。', '2026-06-27T13:06:00+08:00'),
      response('thread-006', 'd', 'member-elder-ye', '叶淑柔', '阿嬷', 'voice', '晓伟啊，蚝烙要多放朥，火要小！周末回来，阿嬷亲手煎给你吃。', '2026-06-27T13:22:00+08:00', 12),
    ],
  },
  {
    id: 'thread-007',
    title: '无米粿又翻车了',
    photoUrl: getAmaPhotoById('interaction-gallery-007').url,
    photoAlt: getAmaPhotoById('interaction-gallery-007').alt,
    photoLabel: '无米粿翻车现场',
    photoMeta: '6月29日 12:15',
    photoTone: 'gold' as const,
    senderId: 'member-chuqing',
    senderName: '郑楚卿',
    initialContent: '救命啊家人们！今天本来想给妈露一手做地道的无米粿，结果水放多了，现在锅里变成了一坨绿色的史莱姆……[捂脸][流泪] 谁能假装没看见？千万别让阿嬷看到这条！',
    initialMethod: 'text' as const,
    latestSnippet: '水多了就当面糊煎饼吃，你做啥妈都爱吃',
    latestAt: '2026-06-29T12:42:00+08:00',
    unread: false,
    responses: [
      response('thread-007', 'a', 'member-chuqing', '郑楚卿', '女儿', 'text', '救命啊家人们！今天本来想给妈露一手做地道的无米粿，结果水放多了，现在锅里变成了一坨绿色的史莱姆……[捂脸][流泪] 谁能假装没看见？千万别让阿嬷看到这条！', '2026-06-29T12:15:00+08:00'),
      response('thread-007', 'b', 'member-xiaowei', '郑晓伟', '孙子', 'text', '妈，你这是在炼丹吗？我这就去给阿嬷点个外卖压压惊。', '2026-06-29T12:22:00+08:00'),
      response('thread-007', 'c', 'member-elder-ye', '叶淑柔', '阿嬷', 'voice', '晓伟妈，没事的啦，水多了就当面糊煎饼吃，你做啥妈都爱吃，别烫着手就行。', '2026-06-29T12:34:00+08:00', 10),
      response('thread-007', 'd', 'member-chuqing', '郑楚卿', '大嫂', 'text', '呜呜呜，妈你还是看到了……还是我婆婆最好！❤️', '2026-06-29T12:42:00+08:00'),
    ],
  },
  {
    id: 'thread-008',
    title: '谁照顾谁呀',
    photoUrl: getAmaPhotoById('interaction-gallery-008').url,
    photoAlt: getAmaPhotoById('interaction-gallery-008').alt,
    photoLabel: '老街市场',
    photoMeta: '今天 10:15',
    photoTone: 'moss' as const,
    senderId: 'member-chuqing',
    senderName: '郑楚卿',
    initialContent: '今天跟老妈去市场挑了靓鸡，还得她老人家出手，选的就是肥啊👍，等大家过年回来我再给你们炖~',
    initialMethod: 'text' as const,
    latestSnippet: '大姐辛苦了，晚上我回老宅陪妈吃饭，留碗鸡汤给我！',
    latestAt: '2026-07-03T10:52:00+08:00',
    unread: false,
    responses: [
      response('thread-008', 'a', 'member-chuqing', '郑楚卿', '女儿', 'text', '今天跟老妈去市场挑了靓鸡，还得她老人家出手，选的就是肥啊👍，等大家过年回来我再给你们炖~', '2026-07-03T10:15:00+08:00'),
      response('thread-008', 'b', 'member-xiaowei', '郑晓伟', '孙子', 'text', '哈哈哈哈，阿嫲虽然眼睛花了，但买菜的眼光永远在线！！', '2026-07-03T10:24:00+08:00'),
      response('thread-008', 'c', 'member-chulong', '郑楚龙', '三叔', 'text', '大姐辛苦了，晚上我回老宅陪妈吃饭，留碗鸡汤给我！', '2026-07-03T10:52:00+08:00'),
    ],
  },
  {
    id: 'thread-009',
    title: '扛标旗那天',
    photoUrl: getAmaPhotoById('interaction-gallery-009').url,
    photoAlt: getAmaPhotoById('interaction-gallery-009').alt,
    photoLabel: '扛标旗初见',
    photoMeta: '7月1日 17:20',
    photoTone: 'peach' as const,
    senderId: 'member-chuqing',
    senderName: '郑楚卿',
    initialContent: '用阿嬷的老照片生成了当年她扛标旗的盛况，也是在这里父亲对她一见钟情，开始了一生的相守',
    initialMethod: 'text' as const,
    latestSnippet: '原来您和阿公也有这么浪漫的故事',
    latestAt: '2026-07-01T18:02:00+08:00',
    unread: false,
    responses: [
      response('thread-009', 'a', 'member-chuqing', '郑楚卿', '女儿', 'text', '用阿嬷的老照片生成了当年她扛标旗的盛况，也是在这里父亲对她一见钟情，开始了一生的相守', '2026-07-01T17:20:00+08:00'),
      response('thread-009', 'b', 'member-elder-ye', '叶淑柔', '阿嬷', 'voice', '那时候哪里知道你爸在人群里看着我，后来他提起来，我还笑了他好多年。现在看到这个画面，就像又回到了年轻的时候。', '2026-07-01T17:38:00+08:00', 18),
      response('thread-009', 'c', 'member-chuyuan', '郑楚远', '儿子', 'text', '原来父亲记了一辈子的初见是这样的。妈年轻时站在人群里，确实一眼就能看见。', '2026-07-01T17:51:00+08:00'),
      response('thread-009', 'd', 'member-nanzhi', '谢南枝', '泰国姑奶奶', 'text', '嫂子年轻时可精神了，木生哥后来跟我们说，标旗一经过，他的眼睛就再也挪不开了。', '2026-07-01T17:56:00+08:00'),
      response('thread-009', 'e', 'member-xiaowei', '郑晓伟', '孙子', 'text', '阿嬷，原来您和阿公也有这么浪漫的故事！这张图一定要好好保存下来。❤️', '2026-07-01T18:02:00+08:00'),
    ],
  },
  {
    id: 'thread-010',
    title: '楚龙回老宅',
    photoUrl: getAmaPhotoById('interaction-gallery-010').url,
    photoAlt: getAmaPhotoById('interaction-gallery-010').alt,
    photoLabel: '老宅院子',
    photoMeta: '6月29日 15:40',
    photoTone: 'moss' as const,
    senderId: 'member-chulong',
    senderName: '郑楚龙',
    initialContent: '今天回老宅把院子里的青苔清理了一下，免得妈走路滑倒。顺便去老街的茶铺买了妈最爱喝的凤凰单丛，喝茶喽',
    initialMethod: 'text' as const,
    latestSnippet: '楚龙你顺便买只烧鹅回来吧',
    latestAt: '2026-06-29T15:54:00+08:00',
    unread: false,
    responses: [
      response('thread-010', 'a', 'member-chulong', '郑楚龙', '三叔', 'text', '今天回老宅把院子里的青苔清理了一下，免得妈走路滑倒。顺便去老街的茶铺买了妈最爱喝的凤凰单丛，喝茶喽', '2026-06-29T15:40:00+08:00'),
      response('thread-010', 'b', 'member-chuqing', '郑楚卿', '大嫂', 'text', '楚龙你顺便买只烧鹅回来吧，我那个无米粿实在是没法当晚饭了……', '2026-06-29T15:48:00+08:00'),
      response('thread-010', 'c', 'member-xiaowei', '郑晓伟', '孙子', 'text', '哈哈哈哈哈哈三叔救命！', '2026-06-29T15:54:00+08:00'),
    ],
  },
  {
    id: 'thread-011',
    title: '旧怀表又响了一下',
    photoUrl: getAmaPhotoById('interaction-gallery-011').url,
    photoAlt: getAmaPhotoById('interaction-gallery-011').alt,
    photoLabel: '阿公的旧怀表',
    photoMeta: '昨天 10:10',
    photoTone: 'paper' as const,
    senderId: 'member-chulong',
    senderName: '郑楚龙',
    initialContent: '兄弟姐妹们看到找到什么宝贝了，这是阿公当年留下的那个旧怀表！表针早就不转了，但我用拾光叙的【AI旧物焕新】扫了一下，看看复原后多漂亮，还给配了一段滴答滴答的音效。给老妈听的都有点难受了。',
    initialMethod: 'text' as const,
    latestSnippet: '能听到这滴答声，妈已经很知足了',
    latestAt: '2026-07-02T10:42:00+08:00',
    unread: false,
    responses: [
      response('thread-011', 'a', 'member-chulong', '郑楚龙', '三叔', 'text', '兄弟姐妹们看到找到什么宝贝了，这是阿公当年留下的那个旧怀表！表针早就不转了，但我用拾光叙的【AI旧物焕新】扫了一下，看看复原后多漂亮，还给配了一段滴答滴答的音效。给老妈听的都有点难受了。', '2026-07-02T10:10:00+08:00'),
      response('thread-011', 'b', 'member-nanzhi', '谢南枝', '妹妹', 'text', '这怀表我认得！木生哥在曼谷时，做梦都在念叨它，说这是给嫂子的定情信物。', '2026-07-02T10:28:00+08:00'),
      response('thread-011', 'c', 'member-chuqing', '郑楚卿', '姐姐', 'text', '楚龙你快找个好点的师傅修一修，不管花多少钱，咱们给妈修好它！', '2026-07-02T10:36:00+08:00'),
      response('thread-011', 'd', 'member-elder-ye', '叶淑柔', '阿嬷', 'voice', '修不好就算了，能听到这滴答声，妈已经很知足了。', '2026-07-02T10:42:00+08:00', 8),
    ],
  },
  {
    id: 'thread-012',
    title: '曼谷的木棉花',
    photoUrl: getAmaPhotoById('interaction-gallery-012').url,
    photoAlt: getAmaPhotoById('interaction-gallery-012').alt,
    photoLabel: '曼谷木棉花',
    photoMeta: '6月28日 18:00',
    photoTone: 'peach' as const,
    senderId: 'member-nanzhi',
    senderName: '谢南枝',
    initialContent: '看看湄南河边的木棉花今天开了，落了一地红。突然想起老家南山的木棉，应该也是这时候开吧？ 家人们多发点美照啊',
    initialMethod: 'text' as const,
    latestSnippet: '南枝啊，老家的花也开了，等你回来，嫂子给你泡茶',
    latestAt: '2026-06-28T20:10:00+08:00',
    unread: false,
    responses: [
      response('thread-012', 'a', 'member-nanzhi', '谢南枝', '妹妹', 'text', '看看湄南河边的木棉花今天开了，落了一地红。突然想起老家南山的木棉，应该也是这时候开吧？ 家人们多发点美照啊', '2026-06-28T18:00:00+08:00'),
      response('thread-012', 'b', 'member-elder-ye', '叶淑柔', '阿嬷', 'voice', '腿不疼了，你寄的东西总是那么好用。南枝啊，老家的花也开了，等你回来，嫂子给你泡茶。', '2026-06-28T20:02:00+08:00', 12),
      response('thread-012', 'c', 'member-xiaowei', '郑晓伟', '孙子', 'text', '收到指令！快递一到我马上给阿嫲安排上服务！', '2026-06-28T20:10:00+08:00'),
    ],
  },
  {
    id: 'thread-013',
    title: '加班夜里的乡味',
    photoUrl: getAmaPhotoById('interaction-gallery-013').url,
    photoAlt: getAmaPhotoById('interaction-gallery-013').alt,
    photoLabel: '加班晚餐',
    photoMeta: '昨天 21:30',
    photoTone: 'paper' as const,
    senderId: 'member-chuyuan',
    senderName: '郑楚远',
    initialContent: '老妈不用担心我，忙碌的日子也有好好吃饭✌忽然就想咱家里那一口白粥和无米粿啦。等下个月项目结束，一定带素琴和晓伟回老家看您。',
    initialMethod: 'text' as const,
    latestSnippet: '老家的米我都给你留着呢，回来妈给你做',
    latestAt: '2026-07-02T21:52:00+08:00',
    unread: false,
    responses: [
      response('thread-013', 'a', 'member-chuyuan', '郑楚远', '儿子', 'text', '老妈不用担心我，忙碌的日子也有好好吃饭✌忽然就想咱家里那一口白粥和无米粿啦。等下个月项目结束，一定带素琴和晓伟回老家看您。', '2026-07-02T21:30:00+08:00'),
      response('thread-013', 'b', 'member-elder-ye', '叶淑柔', '阿嬷', 'text', '楚远啊，工作再忙也要按时吃饭。老家的米我都给你留着呢，回来妈给你做。', '2026-07-02T21:42:00+08:00'),
      response('thread-013', 'c', 'member-nanzhi', '谢南枝', '妹妹', 'text', '楚远现在出息了，是个大忙人。身体是本钱，要注意休息啊。', '2026-07-02T21:52:00+08:00'),
    ],
  },
  {
    id: 'thread-014',
    title: '素琴寄来的香云纱',
    photoUrl: getAmaPhotoById('interaction-gallery-014').url,
    photoAlt: getAmaPhotoById('interaction-gallery-014').alt,
    photoLabel: '香云纱夏装',
    photoMeta: '6月28日 14:15',
    photoTone: 'peach' as const,
    senderId: 'member-lin-suqin',
    senderName: '林素琴',
    initialContent: '今天逛商场看到几件白色和浅色的香云纱夏装，摸着特别舒服，立刻就给老妈下单了，期待咱妈穿上新衣服美美拍照呀',
    initialMethod: 'text' as const,
    latestSnippet: '白色的衣服衬人，妈喜欢',
    latestAt: '2026-06-28T15:02:00+08:00',
    unread: false,
    responses: [
      response('thread-014', 'a', 'member-lin-suqin', '林素琴', '儿媳', 'text', '今天逛商场看到几件白色和浅色的香云纱夏装，摸着特别舒服，立刻就给老妈下单了，期待咱妈穿上新衣服美美拍照呀', '2026-06-28T14:15:00+08:00'),
      response('thread-014', 'b', 'member-chulong', '郑楚龙', '三叔', 'text', '大嫂费心了，快递到了我去镇上拿给妈。', '2026-06-28T14:42:00+08:00'),
      response('thread-014', 'c', 'member-elder-ye', '叶淑柔', '阿嬷', 'voice', '素琴啊，又乱花钱！不过白色的衣服衬人，妈喜欢，辛苦你了大女儿。', '2026-06-28T15:02:00+08:00', 11),
    ],
  },
  {
    id: 'thread-015',
    title: '曼谷唐人街的药油',
    photoUrl: getAmaPhotoById('interaction-gallery-015').url,
    photoAlt: getAmaPhotoById('interaction-gallery-015').alt,
    photoLabel: '曼谷唐人街',
    photoMeta: '6月29日 10:20',
    photoTone: 'moss' as const,
    senderId: 'member-xie-zehua',
    senderName: '谢泽华',
    initialContent: '今天陪我妈（南枝）逛曼谷的唐人街。老太太走到哪都要看看有没有好点的药油和干货，说要给潮汕的淑柔伯母寄过去，走到哪都惦记着咱们这个家',
    initialMethod: 'text' as const,
    latestSnippet: '也帮我给南枝阿嫲带个好',
    latestAt: '2026-06-29T11:12:00+08:00',
    unread: false,
    responses: [
      response('thread-015', 'a', 'member-xie-zehua', '谢泽华', '南枝儿子', 'text', '今天陪我妈（南枝）逛曼谷的唐人街。老太太走到哪都要看看有没有好点的药油和干货，说要给潮汕的淑柔伯母寄过去，走到哪都惦记着咱们这个家', '2026-06-29T10:20:00+08:00'),
      response('thread-015', 'b', 'member-nanzhi', '谢南枝', '妹妹', 'text', '臭小子别偷拍我！淑柔嫂子腿脚不好，这家的活络油最管用了。', '2026-06-29T10:46:00+08:00'),
      response('thread-015', 'c', 'member-xiaowei', '郑晓伟', '孙子', 'text', '谢谢泽华叔！也帮我给南枝阿嫲带个好！', '2026-06-29T10:58:00+08:00'),
      response('thread-015', 'd', 'member-chulong', '郑楚龙', '三儿子', 'text', '泽华兄弟，上次你们寄来的东西妈用得很好，这次换我给你们寄点潮汕的凤凰单丛过去。', '2026-06-29T11:12:00+08:00'),
    ],
  },
  {
    id: 'thread-016',
    title: '暹罗唐人街旧事',
    photoUrl: getAmaPhotoById('interaction-gallery-016').url,
    photoAlt: getAmaPhotoById('interaction-gallery-016').alt,
    photoLabel: '暹罗唐人街',
    photoMeta: '昨天 18:00',
    photoTone: 'paper' as const,
    senderId: 'member-chulong',
    senderName: '郑楚龙',
    initialContent: '当年父亲就是在这里靠自己的双腿，一车车为千里之外的我们撑起了生活。',
    initialMethod: 'text' as const,
    latestSnippet: '下次我们一起陪阿嬷去看看吧',
    latestAt: '2026-07-02T18:32:00+08:00',
    unread: false,
    responses: [
      response('thread-016', 'a', 'member-chulong', '郑楚龙', '三叔', 'text', '当年父亲就是在这里靠自己的双腿，一车车为千里之外的我们撑起了生活。', '2026-07-02T18:00:00+08:00'),
      response('thread-016', 'b', 'member-elder-ye', '叶淑柔', '阿嬷', 'voice', '你爸年轻的时候就是能吃苦，一个人在外面什么难处都不跟家里说，只说一切都好。', '2026-07-02T18:16:00+08:00', 12),
      response('thread-016', 'c', 'member-chuyuan', '郑楚远', '儿子', 'text', '小时候只知道父亲常年在外，长大了才明白啊。', '2026-07-02T18:24:00+08:00'),
      response('thread-016', 'd', 'member-xiaowei', '郑晓伟', '孙子', 'text', '下次我们一起陪阿嬷去看看吧，也走一走阿公当年走过的路。', '2026-07-02T18:32:00+08:00'),
    ],
  },
  {
    id: 'thread-017',
    title: '孩子第一次学包饺子',
    photoUrl: getAmaPhotoById('interaction-gallery-017').url,
    photoAlt: getAmaPhotoById('interaction-gallery-017').alt,
    photoLabel: '一家人包饺子',
    photoMeta: '今天 11:10',
    photoTone: 'gold' as const,
    senderId: 'member-xiaowei',
    senderName: '郑晓伟',
    initialContent: '今天家里包饺子，小宝看见也非要上手。果不其然都煮破了，一家人喝了碗肉菜粥哈哈~',
    initialMethod: 'text' as const,
    latestSnippet: '孩子第一次学包饺子',
    latestAt: '2026-07-17T11:10:00+08:00',
    unread: false,
    responses: [
      response('thread-017', 'a', 'member-xiaowei', '郑晓伟', '孙子', 'text', '今天家里包饺子，小宝看见也非要上手。果不其然都煮破了，一家人喝了碗肉菜粥哈哈~', '2026-07-17T11:10:00+08:00'),
    ],
  },
  {
    id: 'thread-018',
    title: '曼谷庭院里的牵挂',
    photoUrl: getAmaPhotoById('interaction-gallery-018').url,
    photoAlt: getAmaPhotoById('interaction-gallery-018').alt,
    photoLabel: '曼谷庭院',
    photoMeta: '今天 10:26',
    photoTone: 'peach' as const,
    senderId: 'member-nanzhi',
    senderName: '谢南枝',
    initialContent: '今天曼谷的阳光特别好，院子里的荷花全开啦。下午泽华回来看看我，聊着聊着就想家了。嫂子，老家现在冷不冷？你这几天腿还疼吗？🌸🥭',
    initialMethod: 'text' as const,
    latestSnippet: '等晓伟休假了，让他多带点家里新炒的单丛茶给您带过去',
    latestAt: '2026-07-17T11:02:00+08:00',
    unread: false,
    responses: [
      response('thread-018', 'a', 'member-nanzhi', '谢南枝', '泰国姑奶奶', 'text', '今天曼谷的阳光特别好，院子里的荷花全开啦。下午泽华回来看看我，聊着聊着就想家了。嫂子，老家现在冷不冷？你这几天腿还疼吗？🌸🥭', '2026-07-17T10:26:00+08:00'),
      response('thread-018', 'b', 'member-elder-ye', '叶淑柔', '阿嬷', 'text', '不冷不冷，今天老家也出太阳了。这相片拍得真精神！我腿好多了，晓伟天天给我按呢。', '2026-07-17T10:44:00+08:00'),
      response('thread-018', 'c', 'member-lin-suqin', '林素琴', '大嫂（晓伟妈）', 'text', '姑姑在那边照顾好自己呀，这小院子布置得真雅致。等晓伟休假了，让他多带点家里新炒的单丛茶给您带过去。', '2026-07-17T11:02:00+08:00'),
    ],
  },
  {
    id: 'thread-019',
    title: '周末带家人去看海',
    photoUrl: getAmaPhotoById('interaction-gallery-019').url,
    photoAlt: getAmaPhotoById('interaction-gallery-019').alt,
    photoLabel: '一家人去看海',
    photoMeta: '6月27日 13:30',
    photoTone: 'moss' as const,
    senderId: 'member-xiaowei',
    senderName: '郑晓伟',
    initialContent: '今天带孩子去看海。他捡了满满一桶小贝壳，说要带给太奶奶。',
    initialMethod: 'text' as const,
    latestSnippet: '周末带家人去看海',
    latestAt: '2026-06-27T13:30:00+08:00',
    unread: false,
    responses: [
      response('thread-019', 'a', 'member-xiaowei', '郑晓伟', '孙子', 'text', '今天带孩子去看海。他捡了满满一桶小贝壳，说要带给太奶奶。', '2026-06-27T13:30:00+08:00'),
    ],
  },
]

const sortedAmaInteractionThreads = [...amaInteractionThreads]
  .sort((left, right) => new Date(right.latestAt).getTime() - new Date(left.latestAt).getTime())

export const AMA_LETTER_SCENARIO: PrototypeScenario = {
  id: 'ama-letter',
  label: '给阿嫲的情书',
  familyAvatarSrc: getAmaPhotoById('gallery-104').url,
  memberAvatarSrc: {
    'member-elder-ye': amaAvatar('ye-shurou-avatar.jpg'),
    'member-musheng': amaAvatar('zheng-musheng-avatar.jpg'),
    'member-nanzhi': amaAvatar('xie-nanzhi-avatar.jpg'),
    'member-xiaowei': amaAvatar('zheng-xiaowei-avatar.jpg'),
    'member-chulong': amaAvatar('zheng-chulong-avatar.jpg'),
    'member-chuyuan': amaAvatar('zheng-chuyuan-avatar.jpg'),
    'member-lin-suqin': amaAvatar('lin-suqin-avatar.jpg'),
    'member-chuqing': amaAvatar('zheng-chuqing-avatar.jpg'),
    'member-xie-zehua': amaAvatar('xie-zehua-avatar.jpg'),
  },
  memberAvatarNameMatch: {
    叶淑柔: amaAvatar('ye-shurou-avatar.jpg'),
    阿嫲: amaAvatar('ye-shurou-avatar.jpg'),
    阿嬷: amaAvatar('ye-shurou-avatar.jpg'),
    郑木生: amaAvatar('zheng-musheng-avatar.jpg'),
    木生: amaAvatar('zheng-musheng-avatar.jpg'),
    谢南枝: amaAvatar('xie-nanzhi-avatar.jpg'),
    南枝: amaAvatar('xie-nanzhi-avatar.jpg'),
    郑晓伟: amaAvatar('zheng-xiaowei-avatar.jpg'),
    晓伟: amaAvatar('zheng-xiaowei-avatar.jpg'),
    郑楚龙: amaAvatar('zheng-chulong-avatar.jpg'),
    楚龙: amaAvatar('zheng-chulong-avatar.jpg'),
    郑楚远: amaAvatar('zheng-chuyuan-avatar.jpg'),
    楚远: amaAvatar('zheng-chuyuan-avatar.jpg'),
    林素琴: amaAvatar('lin-suqin-avatar.jpg'),
    素琴: amaAvatar('lin-suqin-avatar.jpg'),
    郑楚卿: amaAvatar('zheng-chuqing-avatar.jpg'),
    楚卿: amaAvatar('zheng-chuqing-avatar.jpg'),
    女儿: amaAvatar('zheng-chuqing-avatar.jpg'),
    谢泽华: amaAvatar('xie-zehua-avatar.jpg'),
    泽华: amaAvatar('xie-zehua-avatar.jpg'),
  },
  familySpace: {
    id: 'family-ama-letter-001',
    name: '叶淑柔的家',
    bindingCode: '195018',
    elderName: '叶淑柔',
  },
  familyInsightSummary:
    '前阵子你总觉得家里互动不多，但上周大家一起通话后，最近明显热闹了：楚龙更常回老宅，楚卿和晓伟接着聊老味道和旧信，南枝也多发了曼谷近况。这是个好趋势，值得夸一夸；下次可以直接表扬大家最近都更常说话了。',
  elderProfile: {
    id: 'elder-ye-profile',
    name: '叶淑柔',
    gender: 'female',
    birthYear: 1940,
    relation: '阿嫲',
    voiceIntroText:
      '叶淑柔阿嫲生在汕头海边，记忆里有老厝、工夫茶、木棉花和一封封跨越南洋的侨批。她现在最想把木生、南枝和这个家的故事讲给晚辈听。',
    interests: ['工夫茶', '潮剧', '侨批', '无米粿', '老照片'],
    avoidTopics: ['强行追问伤心细节', '替她定义遗憾'],
  },
  members: [
    {
      id: 'member-elder-ye',
      name: '叶淑柔',
      relation: '阿嫲',
      avatar: '柔',
      role: 'elder',
      city: '汕头',
      statusLabel: '老宅相框主人',
      weatherLabel: '多云 29°C',
      conversationSummary: '这几天你晚上更常打开旧信和怀表，停得也比白天久。端午前家里人来往多，反而容易想起以前谁在、谁不在。',
      interactionSuggestions: [
        '把今天想起的一个名字先记下来',
        '问问晓伟哪天方便，一起认一认旧照片里的人',
        '和孩子们约个时间，慢慢讲一件旧信里的小事',
      ],
    },
    {
      id: 'member-chuyuan',
      name: '郑楚远',
      relation: '儿子',
      avatar: '远',
      role: 'child',
      city: '深圳',
      statusLabel: '项目忙完就回老家',
      weatherLabel: '多云 28°C',
      conversationSummary: '楚远最近几条留言都拖到了晚上十点以后，之前又念叨项目忙，怕是这段一直在加班。孩子报喜不报忧，累也不肯直说，反倒一遍遍提白粥和无米粿——端午快到了，他嘴上不说想家，胃口倒先回了老家。',
      interactionSuggestions: [
        '楚远最近总是加班错过饭点，提醒他吃口热的',
        '顺着白粥无米粿，问他端午想吃什么',
        '跟他说：累了难了别都自己扛着，妈一直站你这边',
      ],
    },
    {
      id: 'member-lin-suqin',
      name: '林素琴',
      relation: '儿媳',
      avatar: '琴',
      role: 'child',
      city: '深圳',
      statusLabel: '刚给阿嫲寄香云纱',
      weatherLabel: '多云 28°C',
      conversationSummary: '入夏后，素琴问得最多的是衣服轻不轻、鞋底软不软、穿着热不热。她性子细，关心都藏在这些小问题里。',
      interactionSuggestions: [
        '把新衣服穿着舒不舒服告诉素琴',
        '和素琴聊聊最近穿着舒不舒服、鞋子合不合脚',
        '问问素琴最近深圳热不热，她自己有没有照顾好',
      ],
    },
    {
      id: 'member-chulong',
      name: '郑楚龙',
      relation: '三儿子',
      avatar: '龙',
      role: 'child',
      city: '汕头',
      statusLabel: '下午回老宅看阿嫲',
      weatherLabel: '晴 29°C',
      conversationSummary: '入夏后院子容易长青苔，楚龙嘴上嫌麻烦，最近却三次回老宅拍了院子、茶叶和旧物。他不讲甜话，但一直把老宅放在心上。',
      interactionSuggestions: [
        '和楚龙约好，他到老宅时跟你说一声',
        '问问楚龙院子青苔最近还滑不滑',
        '问问他最近身体和睡眠怎么样',
      ],
    },
    {
      id: 'member-chuqing',
      name: '郑楚卿',
      relation: '女儿',
      avatar: '卿',
      role: 'child',
      city: '汕头',
      statusLabel: '又在复刻无米粿',
      weatherLabel: '晴 29°C',
      conversationSummary: '楚卿最近的动态多半是做菜、买菜、送汤。她和你嘴上容易顶两句，但饭菜就是她把话题递回来的方式。',
      interactionSuggestions: [
        '问问楚卿最近家里吃得怎么样',
        '约她哪天一起去市场慢慢挑菜',
        '问问她最近还想学哪一道老味道',
      ],
    },
    {
      id: 'member-xiaowei',
      name: '郑晓伟',
      relation: '孙子',
      avatar: '伟',
      role: 'child',
      city: '深圳',
      statusLabel: '刚数字化一封侨批',
      weatherLabel: '多云 28°C',
      conversationSummary: '晓伟最近发攀岩、做菜翻车这些新鲜事时，也会顺手问旧信和老照片。他是在用年轻人的办法，靠近你的过去。',
      interactionSuggestions: [
        '问问晓伟最近工作之外有什么新鲜事',
        '和晓伟约个十分钟，慢慢看一封旧信',
        '把想补进回忆录的人名，先交给晓伟帮忙整理',
      ],
    },
    {
      id: 'member-nanzhi',
      name: '谢南枝',
      relation: '妹妹',
      avatar: '枝',
      role: 'child',
      city: '曼谷',
      statusLabel: '发来曼谷木棉花',
      weatherLabel: '晴 32°C',
      conversationSummary: '南枝和你一样，不太爱把想念说得太直。她最近总发木棉花、膏药和曼谷天气，快到端午又提到老家的粿和茶。',
      interactionSuggestions: [
        '看见南枝发花照时，和她说说老宅这几天怎么样',
        '和南枝约一个固定时间，哪怕只聊几分钟',
        '下次通话时，问问她最近腿脚和睡眠怎么样',
      ],
    },
    {
      id: 'member-xie-zehua',
      name: '谢泽华',
      relation: '外甥',
      avatar: '华',
      role: 'child',
      city: '曼谷',
      statusLabel: '陪南枝逛唐人街',
      weatherLabel: '晴 32°C',
      conversationSummary: '泽华最近发来的都不是大事，多是陪南枝去唐人街、买药油、挑干货。这些小片段能让你知道，南枝身边有人陪。',
      interactionSuggestions: [
        '问问泽华最近南枝身体怎么样',
        '问问泽华最近唐人街那边天气和生意怎么样',
        '请泽华有空时多拍一点南枝的日常近况',
      ],
    },
  ],
  galleryPhotos: amaGalleryPhotos,
  interactionThreads: sortedAmaInteractionThreads,
  familyExplorationItems: amaWishlistItems,
  familyDynamics: sortedAmaInteractionThreads.map((thread) => ({
    id: `dynamic-${thread.id}`,
    authorId: thread.senderId,
    authorName: thread.senderName,
    relation: thread.responses[0]?.relation || '家人',
    title: thread.title,
    summary: thread.initialContent,
    body: thread.responses.map((response) => response.content).join('\n'),
    photoUrl: thread.photoUrl,
    photoAlt: thread.photoAlt,
    photoUrls: [thread.photoUrl],
    timeLabel: thread.photoMeta,
    placeLabel: thread.id === 'thread-016' || thread.senderId === 'member-nanzhi'
      ? '泰国曼谷'
      : thread.id === 'thread-017'
        ? '深圳家中'
        : thread.id === 'thread-019'
          ? '海边'
          : thread.id === 'thread-007'
            ? '拾光时间胶囊'
            : '汕头老宅',
    voiceDurationSeconds: thread.responses.find((response) => response.method === 'voice')?.durationSeconds,
    replyCount: Math.max(thread.responses.length - 1, 0),
    stickerLabels: [],
    insightTags: [],
    threadId: thread.id,
  })),
  familyWeeklyRecap: {
    id: 'recap-ama-week-0527',
    title: '这一周，阿嫲和家人又说上了好多话',
    subtitle: '19 条家庭动态、11 段语音回应、1 组AI旧照入框',
    coverUrl: getAmaPhotoById('gallery-103').url,
    scenes: [
      { id: 'recap-ama-1', title: '加班夜里的乡味', summary: '楚远夜里吃着白粥和无米粿，隔着相框让阿嫲放心。', photoUrl: getAmaPhotoById('interaction-gallery-013').url },
      { id: 'recap-ama-2', title: '谁照顾谁呀', summary: '楚卿陪阿嫲去市场挑鸡，最后还是被阿嫲上了一课。', photoUrl: getAmaPhotoById('interaction-gallery-008').url },
      { id: 'recap-ama-3', title: '暹罗唐人街旧事', summary: '楚龙把阿公当年在暹罗奔走谋生的旧街景发给全家。', photoUrl: getAmaPhotoById('interaction-gallery-016').url },
      { id: 'recap-ama-4', title: '旧怀表又响了一下', summary: '旧怀表被AI复原出滴答声，木生留下的念想又被听见。', photoUrl: getAmaPhotoById('interaction-gallery-011').url },
      { id: 'recap-ama-5', title: '扛标旗那天', summary: '楚卿用老照片生成阿嫲年轻时扛标旗的盛况，也讲起木生的一见钟情。', photoUrl: getAmaPhotoById('interaction-gallery-009').url },
    ],
  },
  memoryThemes: [
    {
      id: 'theme-childhood',
      title: '根脉与童年',
      subtitle: '出生、家族、童年根脉',
      completedCount: 2,
      totalCount: 8,
      rewardTitle: '老厝童年',
      rewardStatus: 'locked',
      topics: [
        { id: 'topic-name-origin', title: '名字由来', summary: '先从“淑柔”这个名字讲起，聊家里当年怎样盼她长大。', status: 'recommended', updatedAt: '2026-05-24T09:30:00+08:00', photoUrl: getAmaPhotoById('gallery-106').url },
        { id: 'topic-birth-story', title: '出生故事', summary: '出生那天的天气、老屋、接生人和家里人的第一句话。', status: 'unfinished', updatedAt: '2026-05-25T09:30:00+08:00', photoUrl: amaPhoto('still-01.webp') },
        { id: 'topic-ancestor-memory', title: '祖辈记忆', summary: '祖辈留下的规矩、口头禅和家里最早的来处。', status: 'unfinished', updatedAt: '2026-05-26T09:30:00+08:00', photoUrl: amaPhoto('old-letters-table.jpg') },
        { id: 'topic-childhood-home', title: '老家老屋：老厝里的工夫茶与海风', summary: '从汕头海边、天井、青石板和阿爹教的工夫茶讲起。', status: 'completed', updatedAt: '2026-05-12T15:12:00+08:00', photoLabel: '老厝工夫茶', photoUrl: amaMemoir('memoir-01-gongfu-tea.webp') },
        { id: 'topic-childhood-storm', title: '父母身影：风台天的老祠堂与阿爹背影', summary: '讲阿爹背着她躲风台，祠堂里红烛和沉香的味道。', status: 'completed', updatedAt: '2026-05-01T08:00:00+08:00', photoUrl: amaMemoir('memoir-02-storm-temple.webp') },
        { id: 'topic-siblings', title: '兄弟姐妹', summary: '聊南枝和家里同辈人的小时候，哪些事现在还记得清楚。', status: 'locked', updatedAt: '2026-05-27T09:30:00+08:00', photoUrl: getAmaPhotoById('gallery-101').url },
        { id: 'topic-childhood-friends', title: '童年玩伴', summary: '童年时听着红头船汽笛声，在长堤边和玩伴们跑。', status: 'locked', updatedAt: '2026-05-28T09:30:00+08:00', photoUrl: amaPhoto('old-house-couple.jpeg') },
        { id: 'topic-first-photo', title: '第一张照片', summary: '还记不记得第一次被照相时，穿什么衣裳、站在哪里。', status: 'locked', updatedAt: '2026-05-29T09:30:00+08:00', photoUrl: getAmaPhotoById('gallery-105').url },
      ],
    },
    {
      id: 'theme-family',
      title: '成长与青春',
      subtitle: '求学、青春、早年选择',
      completedCount: 2,
      totalCount: 8,
      rewardTitle: '木棉花开的年纪',
      rewardStatus: 'locked',
      topics: [
        { id: 'topic-school-years', title: '上学经历', summary: '有没有背着书包去上学的日子，哪一幕还留在心里。', status: 'recommended', updatedAt: '2026-05-20T18:10:00+08:00', photoUrl: getAmaPhotoById('gallery-106').url },
        { id: 'topic-teacher-classmates', title: '老师同学', summary: '聊一位记得住的老师，或者多年后还会想起的同学。', status: 'unfinished', updatedAt: '2026-05-21T18:10:00+08:00', photoUrl: getAmaPhotoById('gallery-103').url },
        { id: 'topic-first-leaving-home', title: '第一次离家', summary: '第一次独自走远时，带了什么、怕什么、又期待什么。', status: 'unfinished', updatedAt: '2026-05-22T18:10:00+08:00', photoUrl: amaPhoto('still-03.webp') },
        { id: 'topic-young-photo', title: '年轻旧照', summary: '从一张年轻时的照片开始，聊那时的衣裳和眼神。', status: 'locked', updatedAt: '2026-05-23T18:10:00+08:00', photoUrl: getAmaPhotoById('gallery-102').url },
        { id: 'topic-yingge', title: '兴趣爱好：正月里的英歌舞与糖葱薄饼', summary: '锣鼓、人群、旧怀表和那一包甜到心里的糖葱薄饼。', status: 'completed', updatedAt: '2026-04-29T18:10:00+08:00', photoUrl: amaMemoir('memoir-04-yingge-candy.webp') },
        { id: 'topic-first-meet', title: '青春心事：南山木棉红，与未穿的白旗袍', summary: '遇见木生，也想起那件没舍得穿的月白旗袍。', status: 'completed', updatedAt: '2026-05-18T19:32:00+08:00', photoLabel: '月白旗袍', photoUrl: amaMemoir('memoir-03-white-qipao.webp') },
        { id: 'topic-learned-skill', title: '学会的本领', summary: '学裁缝、学持家、学看人情，这些本领是怎么练出来的。', status: 'locked', updatedAt: '2026-05-24T18:10:00+08:00', photoUrl: amaMemoir('memoir-05-needlework.webp') },
        { id: 'topic-first-life-choice', title: '人生第一个选择', summary: '年轻时第一次自己拿主意，是为了什么事。', status: 'locked', updatedAt: '2026-05-25T18:10:00+08:00', photoUrl: getAmaPhotoById('gallery-101').url },
      ],
    },
    {
      id: 'theme-work',
      title: '事业与时代印记',
      subtitle: '工作、岗位、社会参与',
      completedCount: 2,
      totalCount: 8,
      rewardTitle: '日子里的本事',
      rewardStatus: 'locked',
      topics: [
        { id: 'topic-first-job', title: '第一份工作：天未亮的海鲜市', summary: '挑着竹筐去码头，靠自己把孩子拉扯大。', status: 'completed', updatedAt: '2026-05-04T10:24:00+08:00', photoLabel: '扁担和海风', photoUrl: amaMemoir('memoir-06-seafood-market.webp') },
        { id: 'topic-career-years', title: '职业岁月', summary: '那些靠双手过日子的年份，最辛苦也最有底气。', status: 'recommended', updatedAt: '2026-05-23T16:20:00+08:00', photoUrl: amaMemoir('memoir-06-seafood-market.webp') },
        { id: 'topic-master-colleagues', title: '师傅同事', summary: '聊教过她手艺的人，或者一起做活、一起熬过难处的人。', status: 'unfinished', updatedAt: '2026-05-24T16:20:00+08:00', photoUrl: getAmaPhotoById('gallery-103').url },
        { id: 'topic-workplace-memory', title: '单位记忆', summary: '没有正式单位的年月里，码头、灶台和街市就是她的岗位。', status: 'unfinished', updatedAt: '2026-05-25T16:20:00+08:00', photoUrl: amaPhoto('still-04.webp') },
        { id: 'topic-era-events', title: '时代大事', summary: '从侨批断了、物资紧了这些日常变化里，讲时代怎样压到家门口。', status: 'locked', updatedAt: '2026-05-26T16:20:00+08:00', photoUrl: amaPhoto('letter-memory.png') },
        { id: 'topic-hard-time', title: '拿手本领：乱世里的针脚，我的本领是活着', summary: '灶台和缝纫机，是她撑过年月的岗位。', status: 'completed', updatedAt: '2026-05-21T16:20:00+08:00', photoUrl: amaMemoir('memoir-05-needlework.webp') },
        { id: 'topic-honor-regret', title: '荣誉与遗憾', summary: '这一生最想被看见的辛苦，和偶尔还会想起的遗憾。', status: 'locked', updatedAt: '2026-05-27T16:20:00+08:00', photoUrl: amaPhoto('children-old-photo.jpeg') },
        { id: 'topic-life-changing-chance', title: '改变一生的机会', summary: '哪一次机会、哪一次错过，把后来的人生悄悄改了方向。', status: 'locked', updatedAt: '2026-05-28T16:20:00+08:00', photoUrl: amaPhoto('still-06.webp') },
      ],
    },
    {
      id: 'theme-neighborhood',
      title: '成家与牵挂',
      subtitle: '伴侣、婚姻、子女、家庭责任',
      completedCount: 2,
      totalCount: 8,
      rewardTitle: '隔海家书',
      rewardStatus: 'locked',
      topics: [
        { id: 'topic-first-acquaintance', title: '初次相识', summary: '第一次注意到木生，是在哪个场景、他当时是什么样子。', status: 'recommended', updatedAt: '2026-05-25T17:16:00+08:00', photoUrl: getAmaPhotoById('gallery-102').url },
        { id: 'topic-love-story', title: '恋爱故事', summary: '那时没有太多漂亮话，但有没有一件事让她心里发甜。', status: 'unfinished', updatedAt: '2026-05-26T17:16:00+08:00', photoUrl: amaMemoir('memoir-04-yingge-candy.webp') },
        { id: 'topic-wedding-memory', title: '婚礼记忆', summary: '成亲那天穿什么、谁来帮忙、哪句话最忘不了。', status: 'unfinished', updatedAt: '2026-05-27T17:16:00+08:00', photoUrl: amaPhoto('album-young-couple.jpg') },
        { id: 'topic-partner-temper', title: '伴侣性格', summary: '聊木生的脾气、沉默、体贴，和他最像自己的哪一面。', status: 'locked', updatedAt: '2026-05-28T17:16:00+08:00', photoUrl: getAmaPhotoById('interaction-gallery-011').url },
        { id: 'topic-first-family-property', title: '第一份家当', summary: '一口锅、一张桌、一只铁皮盒，也能撑起一个新家。', status: 'locked', updatedAt: '2026-05-29T17:16:00+08:00', photoUrl: amaPhoto('old-letters-table.jpg') },
        { id: 'topic-raising-children', title: '养育子女', summary: '孩子小时候最让人操心的事，后来反倒成了最想念的热闹。', status: 'locked', updatedAt: '2026-05-30T17:16:00+08:00', photoUrl: amaPhoto('children-old-photo.jpeg') },
        { id: 'topic-first-trip', title: '共同吃过的苦：唐人街的代笔老先生', summary: '南枝为了守住这个家，跑去找同一位老先生继续写信。', status: 'completed', updatedAt: '2026-05-06T14:10:00+08:00', photoUrl: amaMemoir('memoir-08-chinatown-scribe.webp') },
        { id: 'topic-old-neighbor', title: '没说出口的话：邮局的代笔信，与瞒了18年的秘密', summary: '木生在南洋托人写信，字迹陪了阿嫲很多年。', status: 'completed', updatedAt: '2026-05-09T08:12:00+08:00', photoUrl: amaMemoir('memoir-07-overseas-letter.webp') },
      ],
    },
    {
      id: 'theme-daily',
      title: '日常与热爱',
      subtitle: '饭桌、手艺、兴趣、朋友、生活方式',
      completedCount: 1,
      totalCount: 8,
      rewardTitle: '一壶茶的回甘',
      rewardStatus: 'locked',
      topics: [
        { id: 'topic-wumiguo', title: '饭桌记忆：灶台上的无米粿，先涩后甜的油柑', summary: '地瓜粉、韭菜、油柑和那只旧紫砂壶。', status: 'completed', updatedAt: '2026-05-19T12:42:00+08:00', photoLabel: '无米粿', photoUrl: amaMemoir('memoir-09-wumiguo.webp') },
        { id: 'topic-signature-dish', title: '拿手菜', summary: '无米粿、蚝烙、鸡汤，哪一道最像阿嫲的手艺。', status: 'recommended', updatedAt: '2026-05-20T09:36:00+08:00', photoUrl: getAmaPhotoById('interaction-gallery-007').url },
        { id: 'topic-mending-repair', title: '缝补修理', summary: '衣服破了、鞋底松了，家里的东西怎样被她一针一线补回来。', status: 'unfinished', updatedAt: '2026-05-21T09:36:00+08:00', photoUrl: amaMemoir('memoir-05-needlework.webp') },
        { id: 'topic-frugal-dignity', title: '节俭与体面', summary: '省是为了过日子，体面是为了让家人抬得起头。', status: 'unfinished', updatedAt: '2026-05-22T09:36:00+08:00', photoUrl: getAmaPhotoById('gallery-104').url },
        { id: 'topic-neighbors-relatives', title: '邻里亲友', summary: '老宅附近哪些邻居最熟，谁常来帮忙、谁常来串门。', status: 'locked', updatedAt: '2026-05-23T09:36:00+08:00', photoUrl: getAmaPhotoById('gallery-104').url },
        { id: 'topic-festival-customs', title: '节庆习俗', summary: '正月、拜祖、做粿、看戏，那些一年一度的热闹。', status: 'locked', updatedAt: '2026-05-24T09:36:00+08:00', photoUrl: amaPhoto('movie-poster-wide.jpg') },
        { id: 'topic-favorite-opera-book', title: '喜欢的歌/戏/书', summary: '她最爱听哪段潮剧，哪句唱词一响就会跟着哼。', status: 'locked', updatedAt: '2026-05-25T09:36:00+08:00', photoUrl: amaPhoto('still-08.webp') },
        { id: 'topic-dearest-object', title: '最舍不得的物件', summary: '旧紫砂壶、侨批、怀表，哪一样最舍不得放下。', status: 'locked', updatedAt: '2026-05-26T09:36:00+08:00', photoUrl: getAmaPhotoById('interaction-gallery-011').url },
      ],
    },
    {
      id: 'theme-new-life',
      title: '荣休后的新生活',
      subtitle: '退休后的人生变化与继续生长',
      completedCount: 2,
      totalCount: 8,
      rewardTitle: '大屏幕里的团圆',
      rewardStatus: 'locked',
      topics: [
        { id: 'topic-children-left-home', title: '子女离家', summary: '孩子一个个长大离家后，老宅第一次安静下来是什么感觉。', status: 'recommended', updatedAt: '2026-05-19T18:12:00+08:00', photoUrl: amaPhoto('family-group.jpeg') },
        { id: 'topic-moving-home', title: '搬家迁居', summary: '这一生有没有搬过家，哪些东西不管搬到哪里都要带着。', status: 'unfinished', updatedAt: '2026-05-20T18:12:00+08:00', photoUrl: amaPhoto('album-elder-reunion.png') },
        { id: 'topic-retirement-moment', title: '退休时刻', summary: '真正闲下来的那一天，是轻松，还是忽然有点空。', status: 'unfinished', updatedAt: '2026-05-21T18:12:00+08:00', photoUrl: getAmaPhotoById('gallery-107').url },
        { id: 'topic-body-change', title: '身体变化', summary: '腿脚、眼睛、睡眠慢慢变了，她怎样和身体重新相处。', status: 'locked', updatedAt: '2026-05-22T18:12:00+08:00', photoUrl: getAmaPhotoById('gallery-107').url },
        { id: 'topic-frame-reunion', title: '重新学习：大屏幕里的团圆', summary: '相框让阿嫲每天都能看看孩子，也听见南枝的声音。', status: 'completed', updatedAt: '2026-05-17T20:10:00+08:00', photoLabel: '智能相框', photoUrl: amaPhoto('ama-frame-memory.png') },
        { id: 'topic-opera', title: '老朋友重逢：相框里的大戏，和曼谷来的冬阴功汤', summary: '老屋里重新热闹起来，潮剧、视频和冬阴功汤都进了日常。', status: 'completed', updatedAt: '2026-05-18T18:12:00+08:00', photoUrl: amaPhoto('still-08.webp') },
        { id: 'topic-travel-activity', title: '旅行与活动', summary: '现在还想去哪里看看，或者和家人一起做些什么。', status: 'locked', updatedAt: '2026-05-23T18:12:00+08:00', photoUrl: getAmaPhotoById('interaction-gallery-012').url },
        { id: 'topic-new-wish', title: '现在的小愿望', summary: '每天看看孩子，听听南枝的声音，老屋就没那么安静。', status: 'locked', updatedAt: '2026-05-24T18:12:00+08:00', photoUrl: getAmaPhotoById('gallery-104').url },
      ],
    },
    {
      id: 'theme-heart',
      title: '感悟与传承',
      subtitle: '孙辈、家族记忆、留给未来',
      completedCount: 1,
      totalCount: 8,
      rewardTitle: '留给未来的一封信',
      rewardStatus: 'unlocked',
      topics: [
        { id: 'topic-grandchildren', title: '孙辈故事', summary: '晓伟小时候的淘气、长大后的细心，都可以慢慢讲。', status: 'recommended', updatedAt: '2026-05-24T10:20:00+08:00', photoUrl: getAmaPhotoById('gallery-104').url },
        { id: 'topic-family-photos', title: '家族照片', summary: '从一张全家福开始，补上每个人站在这个家里的位置。', status: 'unfinished', updatedAt: '2026-05-25T09:12:00+08:00', photoUrl: amaPhoto('family-group.jpeg') },
        { id: 'topic-dialect-catchphrase', title: '方言口头禅', summary: '她常说的潮汕话、常念的叮嘱，都是家里的声音。', status: 'unfinished', updatedAt: '2026-05-26T09:12:00+08:00', photoUrl: getAmaPhotoById('gallery-102').url },
        { id: 'topic-unspoken-word', title: '家训与祝福：留给未来的一封信', summary: '把南枝写进家谱，也把先涩后甜的家训留给晚辈。', status: 'completed', updatedAt: '2026-05-26T09:12:00+08:00', photoUrl: amaPhoto('still-09.webp') },
        { id: 'topic-questions-answers', title: '想问想答', summary: '晚辈最想问阿嫲的问题，阿嫲也可以反过来问孩子。', status: 'locked', updatedAt: '2026-05-28T09:12:00+08:00', photoUrl: amaPhoto('ama-frame-memory.png') },
        { id: 'topic-shared-supplement', title: '共同补充', summary: '一家人一起补细节，把记忆从一个人的讲述变成全家的记录。', status: 'locked', updatedAt: '2026-05-29T09:12:00+08:00', photoUrl: getAmaPhotoById('interaction-gallery-003').url },
        { id: 'topic-future-letter', title: '留给未来的一封信', summary: '如果给未来的孩子留一封信，她最想写下哪几句话。', status: 'locked', updatedAt: '2026-05-30T09:12:00+08:00', photoUrl: amaPhoto('still-09.webp') },
        { id: 'topic-family-tree', title: '家谱树补完', summary: '把南枝端端正正写进家谱，也把这个家的来处讲清楚。', status: 'locked', updatedAt: '2026-05-31T09:12:00+08:00', photoUrl: getAmaPhotoById('gallery-107').url },
      ],
    },
  ],
  memoryStories: [
    {
      id: 'story-childhood-home',
      type: 'topic',
      title: '老厝里的工夫茶与海风',
      themeTitle: '根脉与童年',
      generatedAt: '2026-05-12T15:18:00+08:00',
      photoUrl: amaMemoir('memoir-01-gongfu-tea.webp'),
      photoCaption: 'AI生图：潮汕老厝里的工夫茶。',
      readDurationSeconds: 300,
      isNew: false,
      body: [
        '我是生在汕头海边的一个普通囡仔。记忆里的老家，是一座带着天井的老厝，院子里的青石板缝里总长着倔强的青苔，一到雨天就滑得很。',
        '我阿爹是个极重规矩的潮汕男人。他教我的第一件事不是认字，而是冲工夫茶。关公巡城、韩信点兵，他总说，水要沸，心要静，这茶里的苦涩和回甘，就是人一辈子的味道。',
        '那时候我总和邻居家的女娃们在长堤边跑，听着红头船靠岸的汽笛声，总觉得外面的世界很大。我从没想过，童年时闻惯的海风，还有这杯永远温热的工夫茶，后来竟成了我大半辈子用来解乡愁、守空房的慰藉。',
        '如今对着拾光叙说起这些，机器竟帮我画出了当年老厝的模样。看着那张八仙桌，我仿佛又听到了阿爹咳嗽的声音。',
      ],
    },
    {
      id: 'story-childhood-storm',
      type: 'topic',
      title: '风台天的老祠堂与阿爹背影',
      themeTitle: '根脉与童年',
      generatedAt: '2026-05-01T08:30:00+08:00',
      photoUrl: amaMemoir('memoir-02-storm-temple.webp'),
      photoCaption: 'AI生图：风台天的老祠堂。',
      readDurationSeconds: 180,
      isNew: false,
      body: [
        '我们潮汕海边，每年夏天最怕的就是风台。我还记事时，有一年风特别大，老厝的瓦片都被掀飞了。',
        '阿爹用宽大的麻布衣把我裹在怀里，顶着狂风暴雨往村里的老祠堂跑。祠堂里挤满了避风的乡亲，到处是红烛和沉香的味道。',
        '那天夜里，外头是海浪拍岸的巨响，里头是阿爹宽阔厚实的后背。他整夜都没合眼，死死抵住被风吹得直晃的木门。',
        '后来我自己成家、带孩子，每当遇到过不去的坎，总能想起那个风台天，想起阿爹抵着门的背影，心里就有了底气。',
      ],
    },
    {
      id: 'story-first-meet',
      type: 'topic',
      title: '南山木棉红，与未穿的白旗袍',
      themeTitle: '成长与青春',
      generatedAt: '2026-05-18T19:40:00+08:00',
      photoUrl: amaMemoir('memoir-03-white-qipao.webp'),
      photoCaption: 'AI生图：木棉花开的青春。',
      readDurationSeconds: 220,
      isNew: false,
      body: [
        '女孩子的青春，总是在不知不觉中到来的。那年南山的木棉花开得像火一样，那是汕头最美的季节，也是我遇见木生的季节。',
        '他是个话不多但眼睛很亮的小伙子。我们没怎么正经约会过，最多就是一前一后走在长堤上。',
        '那段日子里，我偷偷学会了裁缝的本领，给自己做了一件月白色的旗袍，针脚缝得很细，心里全是对未来的期盼。',
        '我本想在成亲那天，或者等他出海风风光光回来那天穿给他看。可后来为了生计，为了这个家，这件旗袍再也没舍得穿上身。它被我叠在樟木箱底，从挺括放到了发脆。',
      ],
    },
    {
      id: 'story-yingge',
      type: 'topic',
      title: '正月里的英歌舞与糖葱薄饼',
      themeTitle: '成长与青春',
      generatedAt: '2026-04-29T18:20:00+08:00',
      photoUrl: amaMemoir('memoir-04-yingge-candy.webp'),
      photoCaption: 'AI生图：正月英歌舞与糖葱薄饼。',
      readDurationSeconds: 210,
      isNew: false,
      body: [
        '那时的日子虽然清苦，但每年正月村里的庙会是最高兴的。那年戏台下在跳英歌舞，锣鼓喧天，人挤着人。',
        '我个子矮，踮着脚也看不见。突然，有个高个子的小伙子在我前面挡住了推搡的人群，回头冲我憨憨地笑。他就是木生。',
        '那天散场后，他花了帮人扛三天麻袋才赚来的钱，给我买了一包糖葱薄饼。薄饼卷着芝麻和麦芽糖，咬一口，甜到了心里。',
        '他没说过什么山盟海誓的漂亮话，只在决定下南洋的前一晚，把一块旧怀表交给我，说表滴答滴答走，就当是他陪着我。那包饼的甜味，我记了一辈子。',
      ],
    },
    {
      id: 'story-hard-time',
      type: 'topic',
      title: '乱世里的针脚，我的本领是活着',
      themeTitle: '事业与时代印记',
      generatedAt: '2026-05-21T16:32:00+08:00',
      photoUrl: amaMemoir('memoir-05-needlework.webp'),
      photoCaption: 'AI生图：煤油灯下的针脚。',
      readDurationSeconds: 210,
      isNew: false,
      body: [
        '现在的年轻人讲究事业，但在我们那个战火纷飞的年代，女人最大的事业，就是把一大家子的命保住。',
        '木生走后，我一个人撑起这个家。我没有单位，没有耀眼的头衔，我唯一的岗位就是灶台和缝纫机。',
        '我给人家做衣服、纳鞋底，手指头被针扎得全是茧子。遇到饥荒年，连地瓜面都买不起。我不认命，我的拿手本领就是熬。',
        '时代的大事我一个妇道人家不懂，我只知道，不管世道多乱，只要灶台上的火不灭，这家就散不了。这就是我这辈子最骄傲的荣誉。',
      ],
    },
    {
      id: 'story-first-job',
      type: 'topic',
      title: '天未亮的海鲜市',
      themeTitle: '事业与时代印记',
      generatedAt: '2026-05-04T10:30:00+08:00',
      photoUrl: amaMemoir('memoir-06-seafood-market.webp'),
      photoCaption: 'AI生图：天未亮的海鲜市。',
      readDurationSeconds: 190,
      isNew: false,
      body: [
        '木生去了暹罗后，遇到战乱，侨批断过好一阵子。家里三个孩子嗷嗷待哺，我不能干等。',
        '我人生第一份工作，就是在天还没亮的时候，提着竹筐去码头进鱼丸和虾干，然后再挑到十里外的镇上去卖。海风吹得脸生疼，肩膀被扁担磨出了厚厚的老茧。',
        '有一次下大雨，路滑，我连人带筐摔进了泥水里，鱼丸滚了一地。我坐在泥水里大哭了一场，哭完后，把还能要的鱼丸洗干净，擦干眼泪继续赶路。',
        '后来孩子们都出息了，楚龙不让我再操劳。但他们不知道，当年那个挑着扁担在黑夜里走路的叶淑柔，才是我这辈子最佩服的自己。',
      ],
    },
    {
      id: 'story-old-neighbor',
      type: 'topic',
      title: '邮局的代笔信，与瞒了18年的秘密',
      themeTitle: '成家与牵挂',
      generatedAt: '2026-05-09T08:18:00+08:00',
      photoUrl: amaMemoir('memoir-07-overseas-letter.webp'),
      photoCaption: 'AI生图：铁皮盒里的侨批。',
      readDurationSeconds: 230,
      isNew: false,
      body: [
        '木生没什么文化，他在南洋讨生活，寄回来的侨批都是花钱请邮局的先生代笔写的。每个月，只要看到信封上那方方正正的代笔字迹和红头船的印记，我就知道他平安。',
        '信里总是那几句干巴巴的话：寄银二十，家里买米，我在暹罗勿念。就因为一直是代笔，所以我从未察觉过任何异样。',
        '我怎么会想到呢？1960 年那场劫船意外后，木生就已经不在了。而那之后整整 18 年，那些一样字迹的代笔信，那些按时寄回家的银元，竟是南枝以木生的名义寄回来的。',
        '我守着邮局先生的字迹，读了 18 年鬼魂的情书，却不知道背后藏着另一个女人倾尽所有的善意。',
      ],
    },
    {
      id: 'story-first-trip',
      type: 'topic',
      title: '唐人街的代笔老先生',
      themeTitle: '成家与牵挂',
      generatedAt: '2026-05-06T14:18:00+08:00',
      photoUrl: amaMemoir('memoir-08-chinatown-scribe.webp'),
      photoCaption: 'AI生图：唐人街的代笔信。',
      readDurationSeconds: 230,
      isNew: false,
      body: [
        '木生在曼谷唐人街找了一位姓林的老先生代笔写家书。每个月，看着那工工整整的毛笔字，我就好像听到了木生说话。',
        '1960 年后，信照常寄来，还是那位林老先生的字迹，钱也一分不少。直到晓伟去了泰国我才知道，木生早就遭遇海难了。',
        '南枝这个傻丫头，为了不让我起疑，硬是省吃俭用，每个月不仅凑齐了那笔汇款，还特意跑去唐人街，找到同一位林老先生，继续模仿木生的口吻给我写信。',
        '其实从 60 年起，信里再也没有提过我那块旧怀表了。我心里早就猜到了七分，但我不敢戳破。她用林老先生的字骗了我 18 年，我也用我的沉默，陪她演了 18 年的戏。',
      ],
    },
    {
      id: 'story-wumiguo',
      type: 'topic',
      title: '灶台上的无米粿，先涩后甜的油柑',
      themeTitle: '日常与热爱',
      generatedAt: '2026-05-19T13:00:00+08:00',
      photoUrl: amaMemoir('memoir-09-wumiguo.webp'),
      photoCaption: 'AI生图：无米粿、油柑和旧紫砂壶。',
      readDurationSeconds: 180,
      isNew: false,
      body: [
        '日子再苦，潮汕人的体面不能丢。家里揭不开锅的时候，我就用地瓜粉和一点韭菜，给孩子们做无米粿。出锅时晶莹剔透，孩子们吃得狼吞虎咽，我在旁边看着，心里酸酸的。',
        '后来日子好过了，女儿经常给我买好吃的，但我还是最惦记那口无米粿和家乡的油柑。',
        '油柑这果子，咬下去第一口是酸涩的，涩得人皱眉头，可嚼着嚼着，喉咙里就泛起一股清甜。这多像我这一辈子啊。',
        '我最舍不得的物件，除了木生那些信，就是那个冲茶的旧紫砂壶。只要水一烧开，茶香一飘，我就觉得，生活里的那些苦，总算都被这口热茶给化解了。',
      ],
    },
    {
      id: 'story-frame-reunion',
      type: 'topic',
      title: '大屏幕里的团圆',
      themeTitle: '荣休后的新生活',
      generatedAt: '2026-05-17T20:22:00+08:00',
      photoUrl: amaPhoto('ama-frame-memory.png'),
      photoCaption: 'AI生图：大屏幕里的晚年团圆。',
      readDurationSeconds: 180,
      isNew: false,
      body: [
        '孩子们都成家立业了，晓伟这皮猴子也长大了。我的腿脚大不如前，出不了远门，本以为这辈子就这样守着老宅到头了。',
        '没想到，晓伟去了趟泰国，不仅解开了侨批的秘密，还给我带回了一个亲人，南枝。这个替木生写了 18 年信的傻妹妹。',
        '现在，晓伟给我买了这个叫拾光叙的相框。我只要喊一声找南枝，屏幕上就能看见她在曼谷的样子。我们老姐妹隔着屏幕聊腿疼用什么膏药，聊湄南河的木棉花。',
        '我这把年纪了，身体在变老，但心却好像突然打开了。现在的小愿望很简单，就是每天能在这个发光的屏幕里，看看孩子们，听听南枝的声音。',
      ],
    },
    {
      id: 'story-opera',
      type: 'topic',
      title: '相框里的大戏，和曼谷来的冬阴功汤',
      themeTitle: '荣休后的新生活',
      generatedAt: '2026-05-18T18:24:00+08:00',
      photoUrl: amaPhoto('still-08.webp'),
      photoCaption: 'AI生图：相框里的潮剧与新生活。',
      readDurationSeconds: 190,
      isNew: false,
      body: [
        '退休后的日子本来很无聊。但自从有了拾光叙相框，这老屋里又热闹了。我只要喊一声，相框就能给我放最爱听的潮剧荔镜记。',
        '更让我开心的是，南枝学会了用这玩意儿跟我打视频。上个礼拜，她居然给我寄来一大包泰国香料，在视频里教我做冬阴功汤。',
        '我说又酸又辣吃不惯，她就在屏幕那头笑得前仰后合。几十年的隔海相望，没想到老了老了，我们还能隔着这么个小玻璃板，一起唱潮剧，一起研究做菜。',
        '人老了，身体虽然像生锈的齿轮，但只要心还在跳，每天都是新日子。',
      ],
    },
    {
      id: 'story-unspoken-word',
      type: 'topic',
      title: '留给未来的一封信',
      themeTitle: '感悟与传承',
      generatedAt: '2026-05-26T09:30:00+08:00',
      photoUrl: amaPhoto('still-09.webp'),
      photoCaption: 'AI生图：木棉树下的家族传承。',
      readDurationSeconds: 180,
      isNew: true,
      body: [
        '今天，晓伟在手机上捣鼓了半天，说要把我们家的家谱树补完。我让他把南枝的名字，端端正正地写在我身边。',
        '她用善意撑起了我们家半个世纪的希望，她就是这个家的人。晓伟问我，要给未来的孙辈留句什么家训？我对着相框想了很久。',
        '我说，做人要像那棵南山的木棉树，风吹雨打都不怕，花开得要红、要正。遇到难处了，就吃一颗油柑，喝一杯热茶。要记住，先酸涩，后回甘。',
        '不管以后你们走得多远，哪怕过了番、下了南洋，只要家里的茶还在沸，你们就永远有根。',
      ],
    },
  ],
  frameDeviceStatus: {
    id: 'frame-pad-ye-001',
    deviceName: '老宅客厅相框',
    displayMode: 'elder',
    networkStatus: 'online',
    cacheStatus: 'ready',
    microphoneStatus: 'granted',
    slideshowIntervalSeconds: 30,
    lastSyncedAt: '2026-05-27T10:16:00+08:00',
    weatherLabel: '汕头 多云',
    temperatureCelsius: 29,
  },
  frameConversation: [
    { id: 'frame-line-001', speaker: 'ai', text: '淑柔阿嫲，我在。今天想听潮剧，还是想继续讲木生阿公的侨批？', createdAt: '2026-05-27T10:12:00+08:00' },
    { id: 'frame-line-002', speaker: 'elder', text: '帮我看看晓伟昨天放进来的那封信。', createdAt: '2026-05-27T10:13:00+08:00' },
    { id: 'frame-line-003', speaker: 'ai', text: '好，我已经打开了。信里那句“愿妻儿平安”已经帮你标出来了。', createdAt: '2026-05-27T10:13:20+08:00' },
  ],
  riverStages: [
    {
      id: 'childhood',
      title: '根脉与童年',
      years: '1940-1955',
      summary: '名字、出生、祖辈、老厝和童年玩伴，先把人生最早的根讲清楚。',
      coverUrl: amaMemoir('memoir-01-gongfu-tea.webp'),
      stories: [
        { id: 'childhood-home', title: '老厝里的工夫茶与海风', summary: '天井、青石板和八仙桌上的茶具，是最早的乡愁。', photoUrl: amaMemoir('memoir-01-gongfu-tea.webp'), body: ['叶淑柔生在汕头海边。', '阿爹教她冲工夫茶，也把规矩和韧性一起教给了她。'] },
        { id: 'childhood-friends', title: '长堤边的玩伴', summary: '童年时听着红头船汽笛声，在田埂和长堤边跑。', photoUrl: getAmaPhotoById('gallery-101').url, body: ['那时候外面的世界很大。', '她和邻居家的女娃们在长堤边跑，海风吹得头发乱飞。'] },
      ],
    },
    {
      id: 'youth',
      title: '成长与青春',
      years: '1956-1959',
      summary: '从上学、同学、第一次离家，到兴趣爱好和青春心事。',
      coverUrl: amaMemoir('memoir-03-white-qipao.webp'),
      stories: [
        { id: 'first-meet', title: '南山木棉红', summary: '遇见木生，也想起那件没舍得穿的月白旗袍。', photoUrl: amaMemoir('memoir-03-white-qipao.webp'), body: ['女孩子的青春，总是在不知不觉中到来。', '那年南山木棉花开得像火一样，也是她遇见木生的季节。'] },
        { id: 'white-qipao', title: '月白旗袍没舍得穿', summary: '樟木箱底压着一件没有等到重逢的旗袍。', photoUrl: getAmaPhotoById('interaction-gallery-013').url, body: ['她学会裁缝，给自己做了一件月白旗袍。', '可为了生计和这个家，那件衣服再也没舍得穿上身。'] },
      ],
    },
    {
      id: 'work',
      title: '事业与时代印记',
      years: '1960-1978',
      summary: '第一份工作、职业岁月、时代大事和靠双手撑家的本领。',
      coverUrl: amaMemoir('memoir-05-needlework.webp'),
      stories: [
        { id: 'seafood-market', title: '天未亮的海鲜市', summary: '肩上挑着竹筐，把三个孩子一点点拉扯大。', photoUrl: amaMemoir('memoir-06-seafood-market.webp'), body: ['侨批断过一阵子，她不能干等。', '天还没亮，她就提着竹筐去码头进鱼丸和虾干。'] },
        { id: 'needlework', title: '乱世里的针脚', summary: '灶台和缝纫机，就是那个年代女人的岗位。', photoUrl: amaMemoir('memoir-05-needlework.webp'), body: ['她给人做衣服、纳鞋底，手指头被针扎得全是茧子。', '只要灶台上的火不灭，这个家就散不了。'] },
      ],
    },
    {
      id: 'letters',
      title: '成家与牵挂',
      years: '1979-2025',
      summary: '初次相识、婚礼记忆、养育子女，以及跨越南洋的牵挂。',
      coverUrl: amaMemoir('memoir-07-overseas-letter.webp'),
      stories: [
        { id: 'overseas-letter', title: '邮局的代笔信', summary: '每月寄来的字迹，让她以为木生还平安。', photoUrl: amaMemoir('memoir-07-overseas-letter.webp'), body: ['木生去了南洋，侨批由邮局先生代笔。', '后来她才知道，信后面藏着南枝倾尽所有的善意。'] },
        { id: 'nanzhi-secret', title: '唐人街的代笔老先生', summary: '南枝替姐姐守着远方的牵挂，继续写了十八年的信。', photoUrl: amaMemoir('memoir-08-chinatown-scribe.webp'), body: ['1960 年后，信照常寄来，还是那位林老先生的字迹。', '南枝省吃俭用，把这个漫长的牵挂撑了下去。'] },
      ],
    },
    {
      id: 'daily',
      title: '日常与热爱',
      years: '如今',
      summary: '饭桌味道、拿手菜、缝补修理、节庆习俗和最舍不得的物件。',
      coverUrl: amaMemoir('memoir-09-wumiguo.webp'),
      stories: [
        { id: 'wumiguo', title: '灶台上的无米粿', summary: '日子再苦，潮汕人的体面不能丢。', photoUrl: amaMemoir('memoir-09-wumiguo.webp'), body: ['家里揭不开锅的时候，她就用地瓜粉和韭菜做无米粿。', '后来日子好过了，她还是最惦记那一口家乡味。'] },
        { id: 'oil-gan', title: '先涩后甜的油柑', summary: '咬下去先酸涩，嚼着嚼着喉咙就泛起清甜。', photoUrl: amaMemoir('memoir-09-wumiguo.webp'), body: ['阿嫲说，人这一辈子也像油柑。', '先涩后甜，苦日子总会在热茶里慢慢化开。'] },
      ],
    },
    {
      id: 'new-life',
      title: '荣休后的新生活',
      years: '2026',
      summary: '子女离家、身体变化、重新学习，也包括相框带来的新连接。',
      coverUrl: getAmaPhotoById('gallery-104').url,
      stories: [
        { id: 'frame-reunion', title: '大屏幕里的团圆', summary: '相框让阿嫲每天看看孩子，也听见南枝的声音。', photoUrl: getAmaPhotoById('gallery-104').url, body: ['晓伟给她买了拾光叙相框。', '她只要喊一声找南枝，屏幕上就能看见曼谷那边的亲人。'] },
        { id: 'time-capsule', title: '相框响起木生的声音', summary: '旧信被系统朗读出来，全家在同一刻听见牵挂。', photoUrl: getAmaPhotoById('interaction-gallery-003').url, body: ['时间胶囊提取了侨批里的句子。', '阿嫲坐在相框前听了三遍，最后只说木生，我听到了。'] },
      ],
    },
    {
      id: 'legacy',
      title: '感悟与传承',
      years: '未来',
      summary: '孙辈故事、家族照片、方言口头禅和留给未来的一封信。',
      coverUrl: getAmaPhotoById('gallery-104').url,
      stories: [
        { id: 'family-tree', title: '把南枝写进家谱', summary: '远在曼谷的妹妹，也一直守着这个家。', photoUrl: getAmaPhotoById('gallery-104').url, body: ['晓伟补家谱树时，阿嫲让他把南枝写在自己身边。', '南枝远在曼谷，却把嫂子和这个家一直放在心上。'] },
        { id: 'future-letter', title: '留给未来的一封信', summary: '做人要像南山的木棉树，花开得红，也开得正。', photoUrl: getAmaPhotoById('interaction-gallery-012').url, body: ['不管以后走得多远，只要家里的茶还在沸，就永远有根。', '遇到难处了，就吃一颗油柑，喝一杯热茶。'] },
      ],
    },
  ],
  studyModules: [
    {
      id: 'wishlist',
      title: '愿望清单',
      description: '把想做的事慢慢完成',
      intro: '阿嫲自己的小愿望和全家一起完成的事，都先放在这里，等合适的时候一件件往前推。',
      itemCount: amaWishlistItems.length,
      coverUrl: getAmaPhotoById('interaction-gallery-003').url,
      items: [
        { id: 'ama-wish-preview-nanzhi', title: '每周和南枝说一次话', summary: '姐妹牵挂', note: '不一定聊大事，听见彼此声音就安心。', meta: '已约好', photoUrl: getAmaPhotoById('interaction-gallery-012').url, type: 'wish' as const, updatedAt: '每周日' },
        { id: 'ama-wish-preview-letters', title: '把侨批整理成一本小册子', summary: '家庭共创', note: '旧信、照片和阿嫲的口述一起放进去。', meta: '开始整理', photoUrl: getAmaPhotoById('interaction-gallery-004').url, type: 'wish' as const, updatedAt: '慢慢整理' },
        { id: 'ama-wish-preview-tea', title: '教孩子们冲一次工夫茶', summary: '家传手艺', note: '茶杯要热，水要准，话也要慢慢说。', meta: '想做', photoUrl: getAmaPhotoById('gallery-104').url, type: 'wish' as const, updatedAt: '下次回老宅' },
      ],
    },
    {
      id: 'album',
      title: '个人相册',
      description: 'AI 归档旧照',
      intro: '侨批、老厝、木棉花和家人近况，都按人物、时间和主题收在这里。',
      itemCount: amaGalleryPhotos.length,
      coverUrl: getAmaPhotoById('gallery-103').url,
      items: amaGalleryPhotos.map((photo, index) => ({
        id: `ama-album-${index + 1}`,
        title: photo.title,
        summary: photo.aiTitle || '已归档',
        note: photo.voiceNoteText || photo.metadataSummary,
        meta: photo.aiCategories?.[0] || '家庭照片',
        photoUrl: photo.url,
        type: 'photo' as const,
        updatedAt: index === 0 ? '今天 18:36' : '5月',
      })),
    },
    {
      id: 'recorder',
      title: '岁月留声机',
      description: '珍藏重要声音',
      intro: '这里收着阿嫲留给家人的话，也收着她想慢慢讲完的往事。',
      itemCount: 16,
      coverUrl: getAmaPhotoById('interaction-gallery-003').url,
      items: [
        { id: 'voice-1', title: '一杯回甘茶', summary: '42 秒', note: '孩子们，日子苦的时候，不要急着说过不去。工夫茶第一口也是涩的，要等一等，回甘才会上来。阿嫲这一生等过人，也熬过难，但只要家里还有一盏灯、一壶茶，人就不会散。', meta: '人生叮嘱', photoUrl: getAmaPhotoById('gallery-104').url, durationSeconds: 42, type: 'voice' as const, updatedAt: '今天 09:12' },
        { id: 'voice-2', title: '家是唯一的岸', summary: '55 秒', note: '我是木生。若这段声音能被你们听见，就替我记住一句话：人可以去很远的地方谋生，但心里一定要有岸。那个岸，不是码头，是家里等你的人。愿郑家的孩子，岁岁平安，再无长别离。', meta: '木生', photoUrl: getAmaPhotoById('interaction-gallery-003').url, durationSeconds: 55, type: 'voice' as const, updatedAt: '昨天 20:36' },
        { id: 'voice-3', title: '写给郑家的女孩子', summary: '48 秒', note: '我是南枝。淑柔嫂子教会我，女人不是只会等待的人。她能把孩子养大，把日子撑住，也能把苦咽下去，再慢慢活出回甘。郑家的女孩子们，以后要善良，也要有自己的骨气。', meta: '南枝', photoUrl: getAmaPhotoById('interaction-gallery-012').url, durationSeconds: 48, type: 'voice' as const, updatedAt: '2026年6月29日' },
        { id: 'voice-4', title: '如果你也想离家远行', summary: '46 秒', note: '若有一天你们也要去远方，不必害怕。走出去，是为了把日子过宽；记得回来，是为了不忘自己从哪里来。远方会给你本事，家会给你底气。', meta: '人生叮嘱', photoUrl: getAmaPhotoById('gallery-103').url, durationSeconds: 46, type: 'voice' as const, updatedAt: '2026年6月28日' },
        { id: 'voice-5', title: '给新生命的一声祝福', summary: '38 秒', note: '小囡仔，欢迎你来到这个家。你还不会说话，但已经有人为你翻旧照片、补家谱、泡热茶。愿你以后知道，你不是一个人来到世上的，你身后有很多人爱过、等过、撑过。', meta: '婚姻与新生', photoUrl: getAmaPhotoById('gallery-104').url, durationSeconds: 38, type: 'voice' as const, updatedAt: '2026年6月26日' },
        { id: 'voice-6', title: '给婚礼那天的你们', summary: '44 秒', note: '成家不是两个人从此不分开，而是知道风浪会来，还是愿意并肩坐在一条船上。以后别只记得热闹，也要记得替对方留一盏灯、盛一碗饭、说一句平安。', meta: '婚姻与新生', photoUrl: getAmaPhotoById('gallery-105').url, durationSeconds: 44, type: 'voice' as const, updatedAt: '2025年11月18日' },
        { id: 'voice-7', title: '当你觉得撑不住时', summary: '51 秒', note: '孩子，撑不住的时候，就先把今天过完。饭要吃，觉要睡，门要关好。很多难处，当时看像一整片海，过几年再回头，不过是鞋底带过的一点泥。', meta: '人生叮嘱', photoUrl: getAmaPhotoById('gallery-107').url, durationSeconds: 51, type: 'voice' as const, updatedAt: '2025年8月9日' },
        { id: 'voice-8', title: '别把爱都留到以后', summary: '47 秒', note: '有些话能说的时候，就早点说。想问长辈的事，也早点问。不要总觉得以后还有时间。照片会旧，信纸会黄，声音留下来，人才能像还在身边坐着。', meta: '家书', photoUrl: getAmaPhotoById('gallery-102').url, durationSeconds: 47, type: 'voice' as const, updatedAt: '2025年3月3日' },
        { id: 'voice-9', title: '给晓伟的一句话', summary: '36 秒', note: '小伟，你愿意问，阿嫲就很高兴。一个家最怕的不是有秘密，是后来的人再也不想知道。你把这些名字一个个找回来，阿嫲这一生就不算只停在等待里。', meta: '晓伟', photoUrl: getAmaPhotoById('gallery-104').url, durationSeconds: 36, type: 'voice' as const, updatedAt: '2024年10月14日' },
        { id: 'voice-10', title: '家谱树补完的那天', summary: '45 秒', note: '今天这棵树终于长完整了。木生、南枝、孩子们，还有后来出生的小辈，都有了自己的位置。家谱树不是为了数清楚谁是谁的亲人，是为了让后来的人知道：我们曾这样彼此牵挂。', meta: '家族', photoUrl: getAmaPhotoById('gallery-104').url, durationSeconds: 45, type: 'voice' as const, updatedAt: '2024年4月20日' },
        { id: 'voice-11', title: '那件没穿上的旗袍', summary: '43 秒', note: '我年轻时也爱美，也盼过好日子。那件旗袍没等到该穿的人回来，可它没有白白放在箱底。它提醒我：一个女人的一生，不只有苦等，也有自己的芳华。', meta: '自我回望', photoUrl: getAmaPhotoById('gallery-105').url, durationSeconds: 43, type: 'voice' as const, updatedAt: '2023年12月6日' },
        { id: 'voice-12', title: '留给未来的一封家书', summary: '52 秒', note: '如果以后你们想起我，不必难过。就泡一杯茶，翻一张照片，听一段旧声音。人这一生能留下来的，不是钱财多少，是有人在多年以后，还愿意轻轻说一句：原来她这样爱过我们。', meta: '家书', photoUrl: getAmaPhotoById('interaction-gallery-004').url, durationSeconds: 52, type: 'voice' as const, updatedAt: '2023年5月1日' },
        { id: 'voice-13', title: '给南枝生日那天', summary: '39 秒', note: '南枝，生日这天你要多吃一口甜的。我们姐妹隔着海，也隔过很多年，可我心里一直记得你年轻时坐在茶桌边笑的样子。等这段声音打开，就当嫂子又陪你喝了一杯茶。', meta: '南枝', photoUrl: getAmaPhotoById('gallery-104').url, durationSeconds: 39, type: 'voice' as const, updatedAt: '2026年8月16日', sealed: true, unlockLabel: '南枝生日时拆封', sealedHint: '阿嫲留给妹妹的一段生日声音，还没到约定时间。' },
        { id: 'voice-14', title: '给晓伟成家的日子', summary: '41 秒', note: '小伟，成家以后，记得把日子过得慢一点。会挣钱是本事，会听家里人说话，也是本事。阿嫲不求你们大富大贵，只愿你们吃饭有人等，回家有灯亮。', meta: '晓伟', photoUrl: getAmaPhotoById('gallery-104').url, durationSeconds: 41, type: 'voice' as const, updatedAt: '2028年5月20日', sealed: true, unlockLabel: '晓伟成家那天拆封', sealedHint: '这段叮嘱先存着，等晓伟人生的新阶段再打开。' },
        { id: 'voice-15', title: '老厝团圆那一晚', summary: '46 秒', note: '等你们都回到老厝，茶水烧开，桌子坐满，再打开这段。那时候不管谁从哪里回来，都先别急着说忙，先坐下喝一杯茶。一个家能围在一起，就是最大的福气。', meta: '家族', photoUrl: getAmaPhotoById('interaction-gallery-010').url, durationSeconds: 46, type: 'voice' as const, updatedAt: '2026年10月4日', sealed: true, unlockLabel: '全家再回老厝团圆时拆封', sealedHint: '阿嫲把这段茶桌话留给下一次全家团圆。' },
        { id: 'voice-16', title: '给新生命的小茶杯', summary: '37 秒', note: '小囡仔，等你来到这个家，阿嫲给你留一只小茶杯。你以后会听见很多名字，木生、南枝、楚远、晓伟……这些名字不是负担，是很多人把爱传到你手里。', meta: '婚姻与新生', photoUrl: getAmaPhotoById('gallery-104').url, durationSeconds: 37, type: 'voice' as const, updatedAt: '2029年1月1日', sealed: true, unlockLabel: '家里添新生命时拆封', sealedHint: '给未来小辈的第一声祝福，等家里添新生命再听。' },
      ],
    },
  ],
}
